<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Timecard</name>
   <tag></tag>
   <elementGuidId>62b2a11b-e6c6-4e9e-a495-af02425cf51b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/nav/ol/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Timecard&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>64fc3615-001a-4d57-bf94-405b443cd34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-primary hover:text-primary-accent-300 focus:text-primary-accent-300 active:text-primary-accent-300 dark:text-primary-400 transition duration-150 ease-in-out motion-reduce:transition-none</value>
      <webElementGuid>8e07d900-52ca-41ac-993b-c4fdcd4dfdab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/timecard</value>
      <webElementGuid>85ec86e2-2ccd-4948-b705-320d6481857f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Timecard</value>
      <webElementGuid>23995e98-9588-4055-8b4f-bdae42231410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;mt-2 px-3&quot;]/nav[@class=&quot;w-full rounded-md px-3&quot;]/ol[@class=&quot;list-reset flex&quot;]/a[@class=&quot;text-primary hover:text-primary-accent-300 focus:text-primary-accent-300 active:text-primary-accent-300 dark:text-primary-400 transition duration-150 ease-in-out motion-reduce:transition-none&quot;]</value>
      <webElementGuid>d659a4d3-c1ad-425e-a08d-744cc8a69f41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/nav/ol/a</value>
      <webElementGuid>931e9a5a-ec8a-4c65-9379-15ea9011e2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Timecard')]</value>
      <webElementGuid>341d1050-ee97-48b9-9fca-cfa34df94c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::a[1]</value>
      <webElementGuid>92f28605-732f-42b9-8382-34794fc9b8dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>266b8653-ed9f-40a4-ba03-87816828d85f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[2]/preceding::a[1]</value>
      <webElementGuid>80ed63c2-9a9c-40d7-be0c-25dbcbebbdc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review Timecard'])[1]/preceding::a[1]</value>
      <webElementGuid>58169e06-47ca-4918-a296-fafba73fbb61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Timecard']/parent::*</value>
      <webElementGuid>79233e7d-2fdf-4fa9-ad7b-c8dbe2b01a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/timecard')]</value>
      <webElementGuid>f3e8ddaa-6025-4c7d-8bda-cd33db8b708c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/a</value>
      <webElementGuid>754335f6-96ca-4639-9927-9ae22f5d20dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/timecard' and (text() = 'Timecard' or . = 'Timecard')]</value>
      <webElementGuid>e4c7b36c-552e-47a6-bdf2-7ce52d3cda19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
