<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_EditStudentAvatar</name>
   <tag></tag>
   <elementGuidId>b680b587-52f6-4de8-b444-b34d35362fbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#editAvatar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='editAvatar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#editAvatar</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e9ab7eb-3493-4890-9d3a-18777b418e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editAvatar</value>
      <webElementGuid>1097734a-b5e4-4931-8bce-75fcfd9e4733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modal-toggle</name>
      <type>Main</type>
      <value>avatarModal</value>
      <webElementGuid>a65b0ca2-8436-47e4-8be3-dbb77b1e8495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-mt-6 ml-12</value>
      <webElementGuid>9d2cdf49-aebe-4770-8c6f-bcd0183a60be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editAvatar&quot;)</value>
      <webElementGuid>d5192856-1c89-4c18-9a19-a6bdd79d24a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='editAvatar']</value>
      <webElementGuid>0df50033-e45b-496e-a389-fd046967633e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/main/div[3]/button</value>
      <webElementGuid>c9881346-0b13-4b28-b854-f10bba0a8aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Week Ending:'])[1]/following::button[6]</value>
      <webElementGuid>ea937138-b6ee-4475-b625-ba079dc2a5e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attendance'])[1]/following::button[6]</value>
      <webElementGuid>49278c03-dee1-4d05-83e9-9ad9b46dfc33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Present'])[1]/preceding::button[1]</value>
      <webElementGuid>50ece43a-8658-455d-b02d-0a049cd73503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Absent'])[1]/preceding::button[2]</value>
      <webElementGuid>df9ab711-2363-45ee-b001-fe40e1896c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>30b90cf2-8078-4f6b-943c-69298d71d9cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'editAvatar']</value>
      <webElementGuid>b0ed032c-2f90-4cdf-909d-51a1c28ae21a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
