<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AvatarModal</name>
   <tag></tag>
   <elementGuidId>69b20767-639e-4c11-b6f1-2bf5239babf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.modal-content.relative.bg-white.p-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='avatarModal']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Choose AvatarCancel&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5a1e5375-9b48-4efe-a68f-b8fdf3e963e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-content relative bg-white p-5</value>
      <webElementGuid>03586ab4-2224-4345-a8ee-f34b26458314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose AvatarCancel</value>
      <webElementGuid>154e4d06-9050-4b93-bf85-d2f4d5a432b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;avatarModal&quot;)/div[@class=&quot;modal-content relative bg-white p-5&quot;]</value>
      <webElementGuid>15d0eaef-a2af-4640-b6bd-1f84f175083a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='avatarModal']/div[2]</value>
      <webElementGuid>63cd7363-ff26-48ff-8590-8f2f9bc052a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Time:'])[1]/following::div[4]</value>
      <webElementGuid>7d7f1e07-79e9-4d6f-80ac-1aca48b4a27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Time:'])[1]/following::div[11]</value>
      <webElementGuid>45008238-298e-4a15-8aaa-7f5558f13819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='V1.0.10'])[1]/preceding::div[34]</value>
      <webElementGuid>83e719d8-1140-48b2-ae08-3f40885115d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div[2]</value>
      <webElementGuid>8f8b3678-e306-46f0-8788-2cd5f21e9f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Choose AvatarCancel' or . = 'Choose AvatarCancel')]</value>
      <webElementGuid>b3bb67eb-978b-4ecf-bccd-e4f337a720ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
