<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_profile_avatar</name>
   <tag></tag>
   <elementGuidId>14ae92ca-a5e7-4128-ac14-bbc235194592</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.w-32</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.w-32</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>33acfaec-e4ba-4092-a02d-59748dbc9670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/nurse-avatars/1314916808-01.jpg</value>
      <webElementGuid>b93f57da-607e-4803-9940-00397b6e69bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-32</value>
      <webElementGuid>1e671b2f-222a-4412-8bae-c08e75cd7406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;mt-2 px-3&quot;]/div[@class=&quot;flex p-2&quot;]/img[@class=&quot;w-32&quot;]</value>
      <webElementGuid>f76a9c63-d237-4fbc-be0d-0277e5da12d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/img</value>
      <webElementGuid>527c0a98-cce4-48c8-8fbb-32aaf923a00c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>6bdd8f71-9443-44a0-a663-189bdfc09a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/nurse-avatars/1314916808-01.jpg']</value>
      <webElementGuid>382fc434-439e-4b92-aa7e-484a8ab25387</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
