<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_NurseAvatarMedium</name>
   <tag></tag>
   <elementGuidId>702d2a7d-1354-4141-9306-aed0db8bbeeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.w-32</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/main/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.w-32</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c0ce28ca-7dfa-455e-83b4-4a8cf4be1e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/nurse-avatars/1314916808-06.jpg</value>
      <webElementGuid>bd856f8d-7b2a-4366-ae16-9c3b150977a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-32</value>
      <webElementGuid>2c383f12-3c90-45a5-9a91-1cd87c60f1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;layout&quot;]/main[@class=&quot;main-content&quot;]/main[@class=&quot;mt-2 px-3&quot;]/div[@class=&quot;flex p-2&quot;]/img[@class=&quot;w-32&quot;]</value>
      <webElementGuid>d98d818c-a89e-44c2-b539-d5330be516be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/main/div/img</value>
      <webElementGuid>e88b52b1-149a-41f0-8456-ab5ef1d622fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>2c8da506-7995-4863-bdd2-155fc5fed6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/nurse-avatars/1314916808-06.jpg']</value>
      <webElementGuid>236a18b2-4a5f-4d92-8c70-78787fa99706</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
