<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_NurseAvatarSmall</name>
   <tag></tag>
   <elementGuidId>685e1f45-a975-4bd7-9bb8-d56e8fd39ed2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/main/div/div[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.w-10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d84c2887-69cf-4519-94f1-4d25873c1ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/nurse-avatars/1314916808-01.jpg</value>
      <webElementGuid>e484cbb1-2241-44ef-af4e-07f8dfcdf066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-10</value>
      <webElementGuid>e8993a63-e673-4498-891b-a98833b02b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;layout&quot;]/main[@class=&quot;main-content&quot;]/main[@class=&quot;font mt-2 px-3&quot;]/div[@class=&quot;flex justify-center&quot;]/div[@class=&quot;flex&quot;]/a[1]/img[@class=&quot;w-10&quot;]</value>
      <webElementGuid>b2e38be8-fe18-43b9-aa15-0fc91255e67a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/main/div/div[2]/a/img</value>
      <webElementGuid>2b8c1bfd-b8dd-4631-93a7-034d739f16c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>bd98cbbd-b100-4eb8-8ba3-9a352bb8733f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/nurse-avatars/1314916808-01.jpg']</value>
      <webElementGuid>8f66c524-424f-4a26-8bf6-01468b673f31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
