<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_EndTime</name>
   <tag></tag>
   <elementGuidId>b550d9ea-7492-40ff-8192-95225a441aa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='btn-TimeOut']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-TimeOut</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#btn-TimeOut</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>568c3172-cdb5-4e70-aac8-58157803cf3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border-2 border-black</value>
      <webElementGuid>dff2c5d8-7405-41fe-8798-a30e555a6838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-TimeOut</value>
      <webElementGuid>7274cca3-72ec-48a9-a17e-a3557aaeba29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>19:00</value>
      <webElementGuid>76cd7356-b4c9-4a9d-ac01-5000bf2fddf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-TimeOut&quot;)</value>
      <webElementGuid>6e308c66-f009-47c0-828d-63d88f15aced</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='btn-TimeOut']</value>
      <webElementGuid>69f03aa2-c9c9-47b9-a138-6d2acbe93c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/main/div[4]/div/div[2]/div[2]/div[2]/div/div/select</value>
      <webElementGuid>f7496e29-c6b9-4828-a5d2-befa5041bf5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Time:'])[1]/following::select[1]</value>
      <webElementGuid>12361ab1-1272-4fa4-83e0-18eb22c12c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Time:'])[1]/following::select[3]</value>
      <webElementGuid>aa21b5da-f359-40f5-96ff-5ba2ee119e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='V1.0.5'])[1]/preceding::select[2]</value>
      <webElementGuid>dfd1322c-5246-4004-9078-19d429bbab29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/select</value>
      <webElementGuid>085cd171-d1f2-4a5d-ad60-adb9a7465f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'btn-TimeOut' and (text() = '19:00' or . = '19:00')]</value>
      <webElementGuid>9515a7c4-1d29-479d-9b98-d158127ded52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
