<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Monday</name>
   <tag></tag>
   <elementGuidId>185f10ee-0781-420f-8f59-acf04cc17e85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[3]/div/div[3]/div[2]/table/tbody/tr/td/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Monday&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d0b308f8-ebd0-448b-ab4e-1c75c6dbf330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Monday </value>
      <webElementGuid>36d9d152-4d8c-49fc-b0e7-5abaaa2bf17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;mt-2 px-3&quot;]/div[@class=&quot;mb-16 flex h-1/2 flex-col gap-4 overflow-y-auto&quot;]/div[1]/div[3]/div[@class=&quot;border-2 border-t-0 border-black flex&quot;]/table[@class=&quot;h-fit w-full&quot;]/tbody[1]/tr[@class=&quot;0 p-1&quot;]/td[@class=&quot;w-1/4 border-e-2 border-black p-1 align-top text-xs font-semibold&quot;]/span[1]</value>
      <webElementGuid>944c3e8f-fa2d-4c9b-bce7-44e7b94a69e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[3]/div/div[3]/div[2]/table/tbody/tr/td/span</value>
      <webElementGuid>48b36e5f-9c64-4a6d-9ac7-3e5efb025338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing'])[1]/preceding::span[1]</value>
      <webElementGuid>c78e0924-d524-4bef-9fb6-54d2fc394d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing'])[2]/preceding::span[2]</value>
      <webElementGuid>b869d15f-f599-433d-adaf-f5427a90cee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Monday']/parent::*</value>
      <webElementGuid>5194d7d0-753f-4dbf-a9a9-3e80f26c103c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/table/tbody/tr/td/span</value>
      <webElementGuid>aa452e55-a53e-4683-a487-99de4ef49599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Monday ' or . = ' Monday ')]</value>
      <webElementGuid>e9cf88ee-7b81-472c-8bf3-b73b55be6033</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
