<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Other Actions00000Add Leave of absen_0510bc</name>
   <tag></tag>
   <elementGuidId>a79a1b1d-99cf-47ba-930a-fb3ac6874706</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#other-actions-dropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='other-actions-dropdown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#other-actions-dropdown</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2783d357-3d4f-41c3-a639-8d5d6a7fd7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>other-actions-dropdown</value>
      <webElementGuid>8f876bce-d4a6-4bce-9ad9-93d8dabfb7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-stone-700 w-[100%] border-4 p-2</value>
      <webElementGuid>d87b17fb-4688-424d-bddd-0bdee1c6d534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Other Actions00000Add Leave of absenceProviders Schools Student Details OSCER Work Orders Save Bookmark</value>
      <webElementGuid>32604006-7412-4e4a-aa34-e9496c388363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;other-actions-dropdown&quot;)</value>
      <webElementGuid>09ac977e-be2b-4eb8-b014-e836e7746413</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='other-actions-dropdown']</value>
      <webElementGuid>78528bad-ee06-468c-b40c-6a3ca53f6184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-wrapper']/select[5]</value>
      <webElementGuid>42950403-1bd1-45ba-af06-f5a88be48d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search...'])[1]/following::select[5]</value>
      <webElementGuid>af1f9d8d-409e-4589-ac77-ff22d278cab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kauai'])[1]/following::select[5]</value>
      <webElementGuid>6a0be63b-470b-407e-9c1e-0bd44d645a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='School / Student'])[1]/preceding::select[1]</value>
      <webElementGuid>526e74bc-bfbe-4a46-b553-6d0652068fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0']/parent::*</value>
      <webElementGuid>adff7d94-cad3-4b82-a0e1-04dad010851a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[5]</value>
      <webElementGuid>2ff1a6b9-9eee-48cc-a432-170e4a5f0f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'other-actions-dropdown' and (text() = 'Other Actions00000Add Leave of absenceProviders Schools Student Details OSCER Work Orders Save Bookmark' or . = 'Other Actions00000Add Leave of absenceProviders Schools Student Details OSCER Work Orders Save Bookmark')]</value>
      <webElementGuid>c2855691-0098-47c9-a908-c78726d2150b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
