<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1118 thru 1122This WeekNext WeekMond_cfdbca</name>
   <tag></tag>
   <elementGuidId>5505d2bd-d940-49ca-a993-2f6a7fb04be8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#date_filter_select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='date_filter_select']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#date_filter_select</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>99a745d0-28de-4029-bbb7-4a7cad71695a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-stone-700 w-[100%] border-4 p-2</value>
      <webElementGuid>49020534-72ae-4b68-b3c1-ecee6a297650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>date_filter_select</value>
      <webElementGuid>1128eebb-9791-47bb-b6cd-dbba88f5d028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>11/18 thru 11/22This WeekNext WeekMondayTuesdayWednesdayThursdayFridayNovemberDecemberJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctober</value>
      <webElementGuid>8cba401c-b5d3-4d3b-b225-192b9c9242bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;date_filter_select&quot;)</value>
      <webElementGuid>1ecc4080-42d2-4e92-88a5-1d649d69d279</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='date_filter_select']</value>
      <webElementGuid>da1ee250-1eff-4487-ba6f-f10228854d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-wrapper']/select[3]</value>
      <webElementGuid>993caa99-91ee-43f9-81b8-88be55a53493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search...'])[1]/following::select[3]</value>
      <webElementGuid>8352f1f5-f7bb-41e8-93b6-ddf9d83e9f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kauai'])[1]/following::select[3]</value>
      <webElementGuid>11366c60-509e-4d6c-80a5-397b3b516c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student / School'])[1]/preceding::select[3]</value>
      <webElementGuid>73af021d-65d6-4c8d-bbc6-b5b16b26747b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[3]</value>
      <webElementGuid>79877378-a9cf-4cdb-8440-76397134943f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'date_filter_select' and (text() = '11/18 thru 11/22This WeekNext WeekMondayTuesdayWednesdayThursdayFridayNovemberDecemberJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctober' or . = '11/18 thru 11/22This WeekNext WeekMondayTuesdayWednesdayThursdayFridayNovemberDecemberJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctober')]</value>
      <webElementGuid>3234001b-7345-4819-bab3-678e804e099c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
