<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>actionmenu-handle</name>
   <tag></tag>
   <elementGuidId>040bca2c-8788-4973-ab43-c91917c239d0</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Absent - NoticeAbsent - NCNSWaiting on OrdersProvider Call OutEdit Provider Edit Supervisor Change Color' or . = 'Absent - NoticeAbsent - NCNSWaiting on OrdersProvider Call OutEdit Provider Edit Supervisor Change Color')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':r16:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menu</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>10797a92-82fb-4837-805f-9631acc0ff59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-white min-w-[180px] p-3 border border-blue-gray-50 rounded-md shadow-lg shadow-blue-gray-500/10 font-sans text-sm font-normal text-blue-gray-500 overflow-auto focus:outline-none z-[999]</value>
      <webElementGuid>4c48459d-44eb-4f6f-9274-9878255b4261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>296628dc-276a-4fa6-8a4b-d280ee94ed97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionmenu-handle</value>
      <webElementGuid>37a7f9a4-4603-4cbd-b299-638de507d1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>63ea1f08-3dd5-4426-b12c-a916971f1ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>:r17:</value>
      <webElementGuid>2379c4c2-f898-437e-8b3d-7b7e2f8054fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-orientation</name>
      <type>Main</type>
      <value>vertical</value>
      <webElementGuid>5943512b-7525-4048-8eb9-1dbda70f45ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Absent - NoticeAbsent - NCNSWaiting on OrdersProvider Call OutEdit Provider Edit Supervisor Change Color</value>
      <webElementGuid>f115b378-1e94-42a9-a7d6-02313e08aaaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r16:&quot;)</value>
      <webElementGuid>20f975be-1ba4-4323-8ae0-3878db921283</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[5]/table/thead/tr/th[4]/span/span/span</value>
      <webElementGuid>9db293c4-4e0d-40a4-b10a-8381586070ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r18:']/div</value>
      <webElementGuid>cb743f22-a70a-4c19-9532-9410eba23abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dismiss'])[1]/following::div[1]</value>
      <webElementGuid>c5a7c323-6f9d-4447-b6e9-fcabe7ade28e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div</value>
      <webElementGuid>a9469d8e-92c7-4a53-82bc-22a2a778277d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = ':r16:' and (text() = 'Absent - NoticeAbsent - NCNSWaiting on OrdersProvider Call OutEdit Provider Edit Supervisor Change Color' or . = 'Absent - NoticeAbsent - NCNSWaiting on OrdersProvider Call OutEdit Provider Edit Supervisor Change Color')]</value>
      <webElementGuid>cb5ba4de-1f25-42ed-804a-7c8a3178b878</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
