<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>6afdfc04-1369-46f2-9d9b-70213977398e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':r28:']/div/div/div[2]/div/span[3]/div/span/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div[title=&quot;#702FA1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;#702FA1&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>518c93b3-65a5-4e72-8ffb-91f46e25c2b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>#702FA1</value>
      <webElementGuid>fdb7f8a5-c754-4845-87ab-8890e9c1a43a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cac19abc-b03d-42f6-9a50-66b089d80ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r28:&quot;)/div[@class=&quot;h-[100px]&quot;]/div[@class=&quot;flex items-center mb-2 ml-4 relative&quot;]/div[@class=&quot;absolute z-50 mt-2 p-2 rounded-lg&quot;]/div[@class=&quot;github-picker custom-twitter-picker&quot;]/span[3]/div[1]/span[1]/div[1]</value>
      <webElementGuid>75b027af-10f9-4122-bc2c-cff16c1d2dbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r28:']/div/div/div[2]/div/span[3]/div/span/div</value>
      <webElementGuid>2a3865ec-9d9a-480e-851b-0c83c2c110d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/div/span/div</value>
      <webElementGuid>1a2b03de-c649-4861-b7d5-be0b36b38783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = '#702FA1']</value>
      <webElementGuid>989fedf2-5fe5-4547-bacf-9736309761f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
