<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1_2_3</name>
   <tag></tag>
   <elementGuidId>ffdb9ca6-89f4-44ec-9dd5-463dc576268a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[title=&quot;#A6CAEC&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':r1p:']/div/div[2]/div[2]/div/span[8]/div/span/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;#A6CAEC&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0da05b12-ca47-4ff3-bf87-0f6396e6d692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>#A6CAEC</value>
      <webElementGuid>3b0c4d06-27f4-40ff-abeb-358dcaa543b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7d897d33-8ee1-4a46-9c44-926c7bbdc101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r1p:&quot;)/div[@class=&quot;h-[100px]&quot;]/div[@class=&quot;flex items-center mb-2 ml-4 relative&quot;]/div[@class=&quot;absolute z-50 mt-2 p-2 rounded-lg&quot;]/div[@class=&quot;github-picker custom-twitter-picker&quot;]/span[8]/div[1]/span[1]/div[1]</value>
      <webElementGuid>f6d5d210-a47c-4967-b903-bb2814db9076</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r1p:']/div/div[2]/div[2]/div/span[8]/div/span/div</value>
      <webElementGuid>3fcbb5fe-0490-4a94-8a38-392d66460436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[8]/div/span/div</value>
      <webElementGuid>e642dc07-52e6-4e4a-ad82-e769b6d62683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = '#A6CAEC']</value>
      <webElementGuid>32d2843a-f03c-4352-a4b7-5fa1029adb1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
