<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ruth Nilda Bejarin Adriatico Carolyn Ai_bd533f</name>
   <tag></tag>
   <elementGuidId>c473cc07-5eb2-465a-a382-8d389532d419</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':r1u:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Ruth Nilda Bejarin Adriatico Carolyn Aihara Dreana Aiu&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7f9f5ec0-91e2-4096-8494-69f29b73bc0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r1u:</value>
      <webElementGuid>8fb89d25-4ecd-4b76-b3fe-bf5bde0821bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-white min-w-[180px] p-3 rounded-md shadow-lg shadow-blue-gray-500/10 font-sans text-sm font-normal text-blue-gray-500 overflow-auto focus:outline-none z-[999] border-2 border-black</value>
      <webElementGuid>83c0458e-ba2c-46c5-8aeb-acabe5e8ea39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>fa33a111-68c7-486c-bb93-f4eea01eb1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>d04bb1f2-2c71-4c7f-bf97-8f2b4979b9a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>:r1v:</value>
      <webElementGuid>4336f0ba-3352-4e12-942f-c96ea80e42e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-orientation</name>
      <type>Main</type>
      <value>vertical</value>
      <webElementGuid>d975d4bf-a87b-48a5-b897-bc91b6f56735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ruth Nilda Bejarin Adriatico Carolyn Aihara Dreana Aiu </value>
      <webElementGuid>da784ecc-eb73-43e6-8860-80a17ff3bbec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r1u:&quot;)</value>
      <webElementGuid>eccd276e-f9f8-41bf-b759-b601c53e92b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id=':r1u:']</value>
      <webElementGuid>776eefae-8b9b-41a6-b5ee-56274c9d2355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r20:']/div</value>
      <webElementGuid>aa9fb5ce-e9f8-402f-80f8-5c941c276d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YZ'])[1]/following::div[2]</value>
      <webElementGuid>cbd27478-c46c-467d-bd9c-6914e39337ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WX'])[1]/following::div[2]</value>
      <webElementGuid>70f049eb-f244-46b4-a424-2952139efde3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/div</value>
      <webElementGuid>e1d7a596-7ec3-4e54-af4a-fca9b8bf32e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = ':r1u:' and (text() = 'Ruth Nilda Bejarin Adriatico Carolyn Aihara Dreana Aiu ' or . = 'Ruth Nilda Bejarin Adriatico Carolyn Aihara Dreana Aiu ')]</value>
      <webElementGuid>2a0746a9-606c-41cc-8950-232ac675d6a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
