<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1_2</name>
   <tag></tag>
   <elementGuidId>9925b771-421a-4e57-8563-81ab44901968</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[title=&quot;#702FA1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':r1p:']/div/div/div[2]/div/span[3]/div/span/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;#702FA1&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fdc58145-6aca-42f9-9d42-4ee64d5d597f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>#702FA1</value>
      <webElementGuid>0ef590c9-cbd3-4b96-89d2-2e49c36924ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9f1b0554-e2af-4482-90c1-975a40dfa040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r1p:&quot;)/div[@class=&quot;h-[100px]&quot;]/div[@class=&quot;flex items-center mb-2 ml-4 relative&quot;]/div[@class=&quot;absolute z-50 mt-2 p-2 rounded-lg&quot;]/div[@class=&quot;github-picker custom-twitter-picker&quot;]/span[3]/div[1]/span[1]/div[1]</value>
      <webElementGuid>5aee7d5c-37f0-4d4f-8be4-9bb2c83c639e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r1p:']/div/div/div[2]/div/span[3]/div/span/div</value>
      <webElementGuid>a2786ded-2a3a-444e-a947-4931788d55fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/div/span/div</value>
      <webElementGuid>c5a063f9-833c-4d0b-a6c1-fcac71690ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = '#702FA1']</value>
      <webElementGuid>c07c0e27-6d22-43da-acec-88b0bfb67e22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
