<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Background_background-holder</name>
   <tag></tag>
   <elementGuidId>5ed26779-30e8-4528-a856-e00888a7b101</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='background-holder']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#background-holder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#background-holder</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e6affeaf-ec68-41bb-a478-c87ffe602f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>background-holder</value>
      <webElementGuid>f77aeeee-0f70-474d-bd35-cea3c62a6114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-7 w-7 cursor-pointer rounded-lg border-2 border-gray-300</value>
      <webElementGuid>54af03b4-5c07-43bb-9bf0-db28ad39ee77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;background-holder&quot;)</value>
      <webElementGuid>cef314b4-9592-4f5d-93ea-912d9793d166</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='background-holder']</value>
      <webElementGuid>6375131d-6e7e-49ce-ac74-c2b032ea4e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='color-picker-holder']/div[2]/div</value>
      <webElementGuid>8032e46e-b66d-4d95-a27d-50fafddde919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div</value>
      <webElementGuid>41f06198-715f-4b70-ad9a-751144d03aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'background-holder']</value>
      <webElementGuid>8c0a6aef-527c-4b6b-a251-6cead711ebd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
