<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Foreground_foreground-holder</name>
   <tag></tag>
   <elementGuidId>350a1c2f-8946-487f-9f83-f11366a80dd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='foreground-holder']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#foreground-holder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#foreground-holder</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cd9c9bd5-6d15-4c67-b93f-d518fc6e6c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>foreground-holder</value>
      <webElementGuid>45d25321-00d1-4e98-a956-98cab0a61464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-7 w-7 cursor-pointer rounded-lg border-2 border-gray-300</value>
      <webElementGuid>31cc14d0-b273-4624-9a93-6eec7f7fd9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;foreground-holder&quot;)</value>
      <webElementGuid>5f0be0d8-58ff-4439-b069-fc3ad1c4cab3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='foreground-holder']</value>
      <webElementGuid>6a4d9e43-4518-44e2-acfc-23019ee1f9d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='color-picker-holder']/div/div</value>
      <webElementGuid>fd7e5d7a-94b9-4577-9156-0c5ee20a4f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div</value>
      <webElementGuid>e35cab5c-bb28-46f2-9d1d-4a221fc6383c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'foreground-holder']</value>
      <webElementGuid>2a3321ed-eded-4aa4-a614-48cc5d3f269b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
