<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Adam, Paula</name>
   <tag></tag>
   <elementGuidId>b0e4db39-faa8-42ea-a22f-e96e07ed7c02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='providerlist6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#providerlist6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Adam, Paula&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>12cbbdd7-8a81-48db-b809-6702ecfc23b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer hover:bg-gray-200</value>
      <webElementGuid>cadead50-099d-40c9-b3a5-c34f17213770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>providerlist6</value>
      <webElementGuid>f59a26a7-d243-4dd3-a8c0-516e961be414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adam, Paula</value>
      <webElementGuid>dbe52bb3-fff8-4438-a6bd-e7a8b171d7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;providerlist6&quot;)</value>
      <webElementGuid>011612b8-c538-45d1-b894-5441a386235c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='providerlist6']</value>
      <webElementGuid>2cfb4f89-fab8-4c9c-ab8c-19dee0474129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/dialog/div[2]/div/div[2]/h2[7]</value>
      <webElementGuid>7cb4d7a0-13c6-4833-8d34-4418babf4625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Adam']/parent::*</value>
      <webElementGuid>46f7d75b-919c-46f7-94d2-54e5b1e30eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2[7]</value>
      <webElementGuid>357e1899-2ba2-4b83-92bb-2bc942859499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'providerlist6' and (text() = 'Adam, Paula' or . = 'Adam, Paula')]</value>
      <webElementGuid>210b91ad-d66a-4804-abff-bdd6a00bf79e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
