<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Cameros, Rachel</name>
   <tag></tag>
   <elementGuidId>ffdd1697-b99d-40ee-b668-e1cd1f31627d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='providerlist8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#providerlist8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Cameros, Rachel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>44bc2af4-1bbb-48a8-934a-9bed55169c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer hover:bg-gray-200</value>
      <webElementGuid>2bfd14cc-5799-40f2-b99e-d4ee81ebc6e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>providerlist8</value>
      <webElementGuid>63e7e4ff-6408-4449-9f19-fe45c8598bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cameros, Rachel</value>
      <webElementGuid>135b5292-de2d-4cbc-b44a-7d98ccb3d621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;providerlist8&quot;)</value>
      <webElementGuid>7da4f273-824f-4d20-a81c-1c9f36e12dc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='providerlist8']</value>
      <webElementGuid>a8dfad72-a9c2-46fe-b633-7d53e51242fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/dialog/div[2]/div/div/h2[9]</value>
      <webElementGuid>ef5843ab-5b16-4217-9762-9c8125d198dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cameros']/parent::*</value>
      <webElementGuid>73b7557b-48a5-4d7f-b623-5c5bf588a357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2[9]</value>
      <webElementGuid>9c59e8da-ae4b-4dc1-b152-3993a9b3b2fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'providerlist8' and (text() = 'Cameros, Rachel' or . = 'Cameros, Rachel')]</value>
      <webElementGuid>593b205f-5e11-44de-bc47-ec3bdc3b0455</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
