<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Wed, 1127 0800 - 1330_master-checkbox_99983e</name>
   <tag></tag>
   <elementGuidId>19b46642-f15b-4435-8526-947d3b9270f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='master-checkbox-toggle226218']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#master-checkbox-toggle226218</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#master-checkbox-toggle226218</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6720f46f-7c72-49b9-8e20-5cc8c050c1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>master-checkbox-toggle226218</value>
      <webElementGuid>fdc06114-8d43-47c5-92d0-fb8361f7f93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1e813cc1-7334-4b67-8f79-dbadc74e6678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;master-checkbox-toggle226218&quot;)</value>
      <webElementGuid>9596c370-39dc-4ac4-951a-f576b152f15b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='master-checkbox-toggle226218']</value>
      <webElementGuid>475de182-5491-4594-8609-40fdf14727b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr-main-2']/td[4]/div/input</value>
      <webElementGuid>9ad0b1e8-09ae-407a-8abc-580e73ebcd00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/div/input</value>
      <webElementGuid>3dd8db2d-edbc-4f67-a24c-43667de0af36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'master-checkbox-toggle226218' and @type = 'checkbox']</value>
      <webElementGuid>e285cb71-0b68-45b8-9ad3-22bd6739e807</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
