<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mon, 1125 0800 - 1415_master-checkbox_5083b2</name>
   <tag></tag>
   <elementGuidId>c2eaa22f-54fc-48b2-b000-04e25558f00f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='master-checkbox-toggle226216']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#master-checkbox-toggle226216</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#master-checkbox-toggle226216</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eee70767-cafb-4bb0-bcdc-25d72e581298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>master-checkbox-toggle226216</value>
      <webElementGuid>3dbe8883-3901-4d26-b4a2-b4be5ce63ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bd88a6f9-bc8e-4032-bd5c-ae94c0623282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;master-checkbox-toggle226216&quot;)</value>
      <webElementGuid>7c741bdf-afde-4dd4-a631-cf5ffecaf4a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='master-checkbox-toggle226216']</value>
      <webElementGuid>ce17c33c-6a13-493b-ba10-416365aecca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr-main-0']/td[4]/div/input</value>
      <webElementGuid>ea39552f-51ac-4c43-9cff-628f34221ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/input</value>
      <webElementGuid>53ac6f6b-9187-4654-99bb-1e330e91fb08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'master-checkbox-toggle226216' and @type = 'checkbox']</value>
      <webElementGuid>d59aad65-4bce-4fe2-99e8-0ef5535b35ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
