<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tue, 1015 0800 - 1415_master-checkbox_1dd056</name>
   <tag></tag>
   <elementGuidId>e1720991-f3a1-4d5b-859e-d4eb2d8f0c9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#master-checkbox-toggle164810</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='master-checkbox-toggle164810']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#master-checkbox-toggle164810</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c080bcbc-62cb-4f55-9295-09edf130fd8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>master-checkbox-toggle164810</value>
      <webElementGuid>e1a8be49-7551-4100-8d76-9a2358f40ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a4b452f7-71c3-4884-a00c-f66fcbc9ca35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;master-checkbox-toggle164810&quot;)</value>
      <webElementGuid>f643d730-e00b-4113-ab4f-8338186558c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='master-checkbox-toggle164810']</value>
      <webElementGuid>eb49e695-f7bb-470b-a712-b24f8da8d0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr-main-0']/td[4]/div/input</value>
      <webElementGuid>31eaf00f-7135-4098-be2d-72b1c7be3ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/input</value>
      <webElementGuid>2bb3c322-fca5-470f-b982-42f116784b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'master-checkbox-toggle164810' and @type = 'checkbox']</value>
      <webElementGuid>247e189f-1a10-45ce-b486-239a186bb38a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
