<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fri, 1122 1100 - 1130_master-checkbox_e7591c</name>
   <tag></tag>
   <elementGuidId>6a6579fa-ec80-4413-8b7f-8f5e7a74b362</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='master-checkbox-toggle233226']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#master-checkbox-toggle233226</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#master-checkbox-toggle233226</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4c158d2-1f26-4b45-90f5-84d63a6297d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>master-checkbox-toggle233226</value>
      <webElementGuid>9476ae93-b33b-4478-975f-dcc3135715ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>04d03cb9-e622-4892-aa71-65e58a2e8ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;master-checkbox-toggle233226&quot;)</value>
      <webElementGuid>a4a0e038-ce27-4ec1-9dcb-de0aac53784c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='master-checkbox-toggle233226']</value>
      <webElementGuid>77dcb521-1aa4-44b3-9f35-2ac76da6fe51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr-main-12']/td[4]/div/input</value>
      <webElementGuid>4171c169-a091-449c-8f23-bb74fbb65544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td[4]/div/input</value>
      <webElementGuid>e391978e-439a-49ae-9ea3-24d72cdae3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'master-checkbox-toggle233226' and @type = 'checkbox']</value>
      <webElementGuid>3fcb25a6-9165-4cd5-a759-b0c50d8d6108</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
