<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tue, 1015 0730 - 1330_master-checkbox_d799e2</name>
   <tag></tag>
   <elementGuidId>09c844fb-45c3-48e8-b52b-1e8928c0d3ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#master-checkbox-toggle168146</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='master-checkbox-toggle168146']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#master-checkbox-toggle168146</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a25f7757-37b5-4e94-9853-1136867cc7d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>master-checkbox-toggle168146</value>
      <webElementGuid>65dcc111-da29-4cdb-ac9e-edd8ab610730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>652a9bd7-b186-4cd1-a6b0-15d999409e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;master-checkbox-toggle168146&quot;)</value>
      <webElementGuid>e244a504-5d0c-4900-b1bf-ba61cc517632</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='master-checkbox-toggle168146']</value>
      <webElementGuid>c675ba1d-57e9-44e2-8502-931b6bcfbc85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr-main-4']/td[4]/div/input</value>
      <webElementGuid>1d5988b1-7e61-47f8-b271-565c9d8abb7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[4]/div/input</value>
      <webElementGuid>8a6ebb1a-3886-4fcb-a1da-213df9b2e218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'master-checkbox-toggle168146' and @type = 'checkbox']</value>
      <webElementGuid>276c30e3-0e2c-46af-b18f-4b09b9f3f8ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
