<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tue, 1015 0800 - 1300_master-checkbox_4758ea</name>
   <tag></tag>
   <elementGuidId>99c3eb11-8e66-4182-9c91-559cd3a11cbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#master-checkbox-toggle153529</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='master-checkbox-toggle153529']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#master-checkbox-toggle153529</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f3738ef-40bf-4aad-b2bc-1864c0548d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>master-checkbox-toggle153529</value>
      <webElementGuid>336509a8-3dab-412e-b01a-0ca8aee120fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e301523a-4c1d-4a2b-b022-1ffe078650b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;master-checkbox-toggle153529&quot;)</value>
      <webElementGuid>61fe369e-9c21-46d5-92fe-ff118a0a70ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='master-checkbox-toggle153529']</value>
      <webElementGuid>88786df7-71dd-4dfc-8b34-e63256224f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr-main-2']/td[4]/div/input</value>
      <webElementGuid>6fd7a560-a170-4107-99f1-fc85a7be38cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/div/input</value>
      <webElementGuid>70a348ad-f854-4afe-a990-9dea83165907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'master-checkbox-toggle153529' and @type = 'checkbox']</value>
      <webElementGuid>fcb27070-e709-4472-8fae-4b4678395de2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
