<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Suggestions</name>
   <tag></tag>
   <elementGuidId>35b9b569-f2e2-4f33-92d7-927d74fd1bfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#provider-suggestion > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='provider-suggestion']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Suggestions&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>06c4a438-58be-404b-bbb6-9f73d3d05857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Suggestions</value>
      <webElementGuid>d60485a3-aa4e-4f3d-bbb5-a38e32bc4a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;provider-suggestion&quot;)/span[1]</value>
      <webElementGuid>a7bc15ee-caa4-49d7-bec8-f6a2601d7230</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='provider-suggestion']/span</value>
      <webElementGuid>1b9bf079-ce00-40b8-96ab-a4156821c776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dismiss'])[2]/following::span[4]</value>
      <webElementGuid>1d768f5d-e781-4899-982f-309f101e4f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Color'])[1]/following::span[4]</value>
      <webElementGuid>37ddbdb8-6397-4fd0-8cbb-338ed11dbbf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AB'])[1]/preceding::span[4]</value>
      <webElementGuid>4981c96b-b7fb-4f38-a422-2744a8d04f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CD'])[1]/preceding::span[4]</value>
      <webElementGuid>e78e19d3-0811-4dd0-9e86-bf17b6b736de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Suggestions']/parent::*</value>
      <webElementGuid>205bec04-bf7b-4f2a-b145-9a8305c79113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/span</value>
      <webElementGuid>3b81a5e5-5ade-41e6-903b-7499b2a62285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Suggestions' or . = 'Suggestions')]</value>
      <webElementGuid>3591300c-0377-47d7-826d-22225c986b44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
