<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Horizontal</name>
   <tag></tag>
   <elementGuidId>08a56cad-78bd-4222-af91-d9343018e003</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Scheduler/label_Horizontal.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.text-gray-700.font-light.select-none.cursor-pointer.mt-px.ml-3.mb-0</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Scheduler/label_Horizontal.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Horizontal&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>56895a63-a8ee-4311-9adf-f42172232594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>:r0:</value>
      <webElementGuid>8736ad9f-1f60-4491-8118-780d3c5cbce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-gray-700 font-light select-none cursor-pointer mt-px ml-3 mb-0</value>
      <webElementGuid>bec43882-131b-4624-a6f7-0a9942841096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Horizontal</value>
      <webElementGuid>ee22f89b-8a06-4b80-b2e2-82399d3f7ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;px-3&quot;]/div[2]/div[@class=&quot;inline-flex items-center&quot;]/label[@class=&quot;text-gray-700 font-light select-none cursor-pointer mt-px ml-3 mb-0&quot;]</value>
      <webElementGuid>e21c2eb2-e4ed-4a0e-bf3e-5217e89701bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/label</value>
      <webElementGuid>d5229d1e-9649-4156-935d-baea7f24f06a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not found.'])[1]/following::label[3]</value>
      <webElementGuid>72174c5a-c400-4811-9ca8-fb3411e7b6a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Honolulu'])[1]/preceding::label[1]</value>
      <webElementGuid>9b20792d-e34b-4349-801d-ebe782cb126f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Central'])[1]/preceding::label[1]</value>
      <webElementGuid>608b836f-196c-4cad-955d-20d73a19241e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Horizontal']/parent::*</value>
      <webElementGuid>924be314-0478-4ebe-beb0-6b470ce9c9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/label</value>
      <webElementGuid>dbb0f58d-847c-4dde-a038-274a3ff7e9f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Horizontal' or . = 'Horizontal')]</value>
      <webElementGuid>5cb23d63-f45a-4c08-a5fc-3166915863f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
