<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Thu</name>
   <tag></tag>
   <elementGuidId>606ad02b-d7a0-4346-a28b-3fd5be9db291</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='4']/span/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#4 > span > div > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Thu&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7c31ffa7-6102-4177-bc73-f6310c9652f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thu</value>
      <webElementGuid>d241df36-99ac-4621-8773-af4cd1dcc8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4&quot;)/span[1]/div[1]/p[1]</value>
      <webElementGuid>015f3f57-14ca-4605-ab58-d19e952193da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='4']/span/div/p</value>
      <webElementGuid>a0c6ae8c-7f68-43f1-b133-2bfed014bdb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student / School'])[1]/following::p[7]</value>
      <webElementGuid>359e2f64-14ea-41d9-8eb3-4cd8c2481756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search...'])[1]/following::p[7]</value>
      <webElementGuid>06b9e9d5-e92c-4114-b0e9-8dee848e9720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aina Haina'])[2]/preceding::p[4]</value>
      <webElementGuid>eafa6089-8f16-4b3f-b28f-a4dedbc0f3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jay-Funaki, Nya'])[2]/preceding::p[4]</value>
      <webElementGuid>7e603d9a-4ff8-4661-b863-9e90a290656a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thu']/parent::*</value>
      <webElementGuid>22c19a3d-749a-4513-aac7-40054a28f2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[5]/span/div/p</value>
      <webElementGuid>7b6890e1-1ce9-4d01-b9c3-a65870e114be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Thu' or . = 'Thu')]</value>
      <webElementGuid>a0b60f40-0bc6-4d25-9017-4fabab72d69e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
