<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All SchoolsBaldwin HighChiefess Kama_869a49</name>
   <tag></tag>
   <elementGuidId>82263fe6-fe56-4423-9381-5257b7666aa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='school_filter_select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#school_filter_select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#school_filter_select</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d399b3eb-4480-4190-91b4-117bcd000312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>school_filter_select</value>
      <webElementGuid>7d133f02-dc8a-49a1-aad9-1a8c1d358883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-[100%]</value>
      <webElementGuid>377ef29e-5777-45b4-92df-8b63df55d465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All SchoolsBaldwin HighChiefess Kamakahelei MSChiefess Kapiolani ElemHaikuHilo HighHilo InterHilo Union IaoIao Intermediate SchoolKahakaiKahului ElementaryKalanianaole Elem &amp; InterKapa'a ElementaryKapa'a HighKapa'a MiddleKauai HighKaunakakaiKeaauKeaau Middle Kealakehe Elem.KeaukahaKeonepokoKing Kaumualii Elem.KohalaKona Pacific PCSKonawaena Elem.Konawaena MiddleLahaina InterLanai High &amp; ElemLihikaiMakawaoMaui Waena InterMountain View Elem.NaalehuPomaikaiPrincess NahienaenaPukalaniPuu KukuiWaiakea HighWaiakea InterWaiakeawaenaWaiheeWaikoloa Elem &amp; MiddleWaimea Canyon Middle</value>
      <webElementGuid>026f843e-1cc6-4e78-8b97-3feb7fde50cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;school_filter_select&quot;)</value>
      <webElementGuid>e67aed5d-4383-40e3-883c-12e3189bef64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='school_filter_select']</value>
      <webElementGuid>917aec8e-0a98-46b2-9a7b-e95eb627211c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[3]/table/thead/tr/th/select</value>
      <webElementGuid>4ce2a035-07ba-4258-b0cb-6a38e1be769f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search...'])[1]/following::select[1]</value>
      <webElementGuid>cf321688-c41b-4a50-bd7c-80027cb967fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outer Island'])[1]/following::select[1]</value>
      <webElementGuid>18f6fbf5-bc86-44e0-acb8-b7b3283c147c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baldwin High'])[2]/preceding::select[4]</value>
      <webElementGuid>db56b2f7-733b-4398-a348-603fe7e90247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Poll, Sean John'])[2]/preceding::select[4]</value>
      <webElementGuid>77588972-27f8-4fc8-bf53-3e609962d431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c112f03b-47bf-4683-985f-c7fd0d5e4912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'school_filter_select' and (text() = concat(&quot;All SchoolsBaldwin HighChiefess Kamakahelei MSChiefess Kapiolani ElemHaikuHilo HighHilo InterHilo Union IaoIao Intermediate SchoolKahakaiKahului ElementaryKalanianaole Elem &amp; InterKapa&quot; , &quot;'&quot; , &quot;a ElementaryKapa&quot; , &quot;'&quot; , &quot;a HighKapa&quot; , &quot;'&quot; , &quot;a MiddleKauai HighKaunakakaiKeaauKeaau Middle Kealakehe Elem.KeaukahaKeonepokoKing Kaumualii Elem.KohalaKona Pacific PCSKonawaena Elem.Konawaena MiddleLahaina InterLanai High &amp; ElemLihikaiMakawaoMaui Waena InterMountain View Elem.NaalehuPomaikaiPrincess NahienaenaPukalaniPuu KukuiWaiakea HighWaiakea InterWaiakeawaenaWaiheeWaikoloa Elem &amp; MiddleWaimea Canyon Middle&quot;) or . = concat(&quot;All SchoolsBaldwin HighChiefess Kamakahelei MSChiefess Kapiolani ElemHaikuHilo HighHilo InterHilo Union IaoIao Intermediate SchoolKahakaiKahului ElementaryKalanianaole Elem &amp; InterKapa&quot; , &quot;'&quot; , &quot;a ElementaryKapa&quot; , &quot;'&quot; , &quot;a HighKapa&quot; , &quot;'&quot; , &quot;a MiddleKauai HighKaunakakaiKeaauKeaau Middle Kealakehe Elem.KeaukahaKeonepokoKing Kaumualii Elem.KohalaKona Pacific PCSKonawaena Elem.Konawaena MiddleLahaina InterLanai High &amp; ElemLihikaiMakawaoMaui Waena InterMountain View Elem.NaalehuPomaikaiPrincess NahienaenaPukalaniPuu KukuiWaiakea HighWaiakea InterWaiakeawaenaWaiheeWaikoloa Elem &amp; MiddleWaimea Canyon Middle&quot;))]</value>
      <webElementGuid>f722ea82-77cb-4747-b86c-19d458b4395f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
