<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Other ActionsAdd SchoolAdd StudentAd_95a9b7</name>
   <tag></tag>
   <elementGuidId>95deb717-f34e-485b-bf62-499d225a7814</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='other-actions-dropdown']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#other-actions-dropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#other-actions-dropdown</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>53ee0753-7be6-4e19-a7d1-a140d87770e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>other-actions-dropdown</value>
      <webElementGuid>43fc88a8-76a4-43c9-b3da-41085d0ca89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-stone-700 w-[100%] border-4 p-2</value>
      <webElementGuid>d342aa00-061e-45f8-a8e3-d3d001e89146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Other ActionsAdd SchoolAdd StudentAdd ProviderAdd WorkorderAdd SupervisorSave Bookmark</value>
      <webElementGuid>b3224cc1-e97a-45f4-8aa6-37db015a048f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;other-actions-dropdown&quot;)</value>
      <webElementGuid>666b684c-3ff6-4afd-bc42-b0e9e2f6aca8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='other-actions-dropdown']</value>
      <webElementGuid>4ddc0ce9-04eb-4f75-89ff-36fc8579b07c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-wrapper']/select[5]</value>
      <webElementGuid>43ba3d25-3253-44c0-830f-6631bc8626bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search...'])[1]/following::select[5]</value>
      <webElementGuid>d533f735-6d13-4a0d-895f-503f25aa7436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kauai'])[1]/following::select[5]</value>
      <webElementGuid>3a28407d-d506-4da7-96d6-5f0e6a5e6b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student / School'])[1]/preceding::select[1]</value>
      <webElementGuid>a6f13ca1-9389-44fe-b083-68d7a98c8d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[5]</value>
      <webElementGuid>6fd7ee6d-e926-4f93-b659-f533c0160c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'other-actions-dropdown' and (text() = 'Other ActionsAdd SchoolAdd StudentAdd ProviderAdd WorkorderAdd SupervisorSave Bookmark' or . = 'Other ActionsAdd SchoolAdd StudentAdd ProviderAdd WorkorderAdd SupervisorSave Bookmark')]</value>
      <webElementGuid>fbe44768-e840-4658-b1bf-bf3719abdf5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
