<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>td_Email</description>
   <name>td_Email</name>
   <tag></tag>
   <elementGuidId>6930cc9e-fca1-41d9-b4da-069297012435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table/tbody/tr[1]/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
