<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>td_ID</description>
   <name>td_ID</name>
   <tag></tag>
   <elementGuidId>447c0e12-cc24-4dc6-9a55-8c9ce3ad5ba9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table/tbody/tr[1]/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
