<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>td_LastName</description>
   <name>td_LastName</name>
   <tag></tag>
   <elementGuidId>113d40e8-5707-4ea6-89b5-60b10b02ef29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table/tbody/tr[1]/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
