<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All Students Alik, Jjbasi Avilla, Li_785878</name>
   <tag></tag>
   <elementGuidId>99569a56-71b5-41a3-987c-0b87cff15f92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='student_filter_select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#student_filter_select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#student_filter_select</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b1b7840d-f931-4967-8751-c1851374dcab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>student_filter_select</value>
      <webElementGuid>75aa750b-38e0-45c3-9b40-4215a3027df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-stone-700 w-[100%] border-4 p-2</value>
      <webElementGuid>c355d3eb-9ee7-47af-a0f0-0269f941a736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Students Alik, Jjbasi Avilla, Lincoln Bair, Honey Borja, Kylcer Bronson, Ari Cacpal, Shenelle Caleb, Helio Choy, Kaylie Danielson, Isaiah Dela Cruz, Channelohan Dillon, Jackson Dillon, Sarah Dinius, Kara Diza, Kyzen Dobrescu, Alexandra Fujiyama, Dayneka Fukuda, Ellen Hahn, Marlee Hallers, Frandawn Haluber, Melissa Harrell, Keahi Hashemi, Jasmin Hiraishi, Wynn Hopkins, Weston Hsiao, Summit Ichikawa, Sen Jay-Funaki, Nya Jay-Funaki, Nolena Koiten, Kayshawn Koki, Skye Kuntz Martin, Cataleya Jade Labuguen, Diani Lambot, Immanuel Langidrik, Daisey Ledo Glade, Paloma Lee, Kristian Machado, Ronnie Mate, Izabelle Mcelfresh, Helixorion Meikei, Angelica Mizuuchi, Chance Mwangin, D-Hearth Nguyen, Khai Nicholas, Duke Nobleza, Jacob Olive, Oriana Orosco Thomas, Akayla Palacpac, Jumar Pang, Josiah Panganiban, Mila Pepper, Nazca Pineda, Ysabelle Ramos, Jayzen Renny, Ersalyn Rof, Rdsapino Romi Cho, Kaia Rosecrans, Rubi Lani Sano, Iten Sarabia, Angelo Sawyer, Johnny Shimamura, Kade Shimoda, Deanna Siakkhasone, ayden Silver, Sanjay Slaymaker, Jayden Smith, Kaylub Takei, Leleo Tamuo, Anfin Tanaka, Kain Taulung-Sanford, Tywan Zephaniah Tully, Teagan Watson, Jordyn Wellbrock, Haliaalohaokalikolehua Winder, Tuunerina Yamachika, Dennis Yim, Elijah Yoshikawa, Micah Yoshino, Kaden Zhou, Chengxian (James) Zolezzi Yanez, tefano</value>
      <webElementGuid>747199d5-5529-4ecc-83f4-0d9a3253a8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;student_filter_select&quot;)</value>
      <webElementGuid>92d89550-b037-4d6b-850b-9310194b6bb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='student_filter_select']</value>
      <webElementGuid>a6c05029-ef12-4e55-9bfd-18da539e9fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-wrapper']/select[2]</value>
      <webElementGuid>d3bc7b2c-8ba7-4fe8-b910-a42a035147d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search...'])[1]/following::select[2]</value>
      <webElementGuid>b5be743a-0b86-462a-9d4f-1b64a72dbcf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outer Island'])[1]/following::select[2]</value>
      <webElementGuid>fe7c1ce0-35fc-42cf-81a1-c1b254c6d8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='School'])[1]/preceding::select[4]</value>
      <webElementGuid>294508a5-2139-4645-b33d-7c1b9c760236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student'])[1]/preceding::select[4]</value>
      <webElementGuid>473881f0-ea24-4406-b041-4eb4e116a168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>670df7ad-4ade-45e0-95ce-6573d7d200b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'student_filter_select' and (text() = 'All Students Alik, Jjbasi Avilla, Lincoln Bair, Honey Borja, Kylcer Bronson, Ari Cacpal, Shenelle Caleb, Helio Choy, Kaylie Danielson, Isaiah Dela Cruz, Channelohan Dillon, Jackson Dillon, Sarah Dinius, Kara Diza, Kyzen Dobrescu, Alexandra Fujiyama, Dayneka Fukuda, Ellen Hahn, Marlee Hallers, Frandawn Haluber, Melissa Harrell, Keahi Hashemi, Jasmin Hiraishi, Wynn Hopkins, Weston Hsiao, Summit Ichikawa, Sen Jay-Funaki, Nya Jay-Funaki, Nolena Koiten, Kayshawn Koki, Skye Kuntz Martin, Cataleya Jade Labuguen, Diani Lambot, Immanuel Langidrik, Daisey Ledo Glade, Paloma Lee, Kristian Machado, Ronnie Mate, Izabelle Mcelfresh, Helixorion Meikei, Angelica Mizuuchi, Chance Mwangin, D-Hearth Nguyen, Khai Nicholas, Duke Nobleza, Jacob Olive, Oriana Orosco Thomas, Akayla Palacpac, Jumar Pang, Josiah Panganiban, Mila Pepper, Nazca Pineda, Ysabelle Ramos, Jayzen Renny, Ersalyn Rof, Rdsapino Romi Cho, Kaia Rosecrans, Rubi Lani Sano, Iten Sarabia, Angelo Sawyer, Johnny Shimamura, Kade Shimoda, Deanna Siakkhasone, ayden Silver, Sanjay Slaymaker, Jayden Smith, Kaylub Takei, Leleo Tamuo, Anfin Tanaka, Kain Taulung-Sanford, Tywan Zephaniah Tully, Teagan Watson, Jordyn Wellbrock, Haliaalohaokalikolehua Winder, Tuunerina Yamachika, Dennis Yim, Elijah Yoshikawa, Micah Yoshino, Kaden Zhou, Chengxian (James) Zolezzi Yanez, tefano' or . = 'All Students Alik, Jjbasi Avilla, Lincoln Bair, Honey Borja, Kylcer Bronson, Ari Cacpal, Shenelle Caleb, Helio Choy, Kaylie Danielson, Isaiah Dela Cruz, Channelohan Dillon, Jackson Dillon, Sarah Dinius, Kara Diza, Kyzen Dobrescu, Alexandra Fujiyama, Dayneka Fukuda, Ellen Hahn, Marlee Hallers, Frandawn Haluber, Melissa Harrell, Keahi Hashemi, Jasmin Hiraishi, Wynn Hopkins, Weston Hsiao, Summit Ichikawa, Sen Jay-Funaki, Nya Jay-Funaki, Nolena Koiten, Kayshawn Koki, Skye Kuntz Martin, Cataleya Jade Labuguen, Diani Lambot, Immanuel Langidrik, Daisey Ledo Glade, Paloma Lee, Kristian Machado, Ronnie Mate, Izabelle Mcelfresh, Helixorion Meikei, Angelica Mizuuchi, Chance Mwangin, D-Hearth Nguyen, Khai Nicholas, Duke Nobleza, Jacob Olive, Oriana Orosco Thomas, Akayla Palacpac, Jumar Pang, Josiah Panganiban, Mila Pepper, Nazca Pineda, Ysabelle Ramos, Jayzen Renny, Ersalyn Rof, Rdsapino Romi Cho, Kaia Rosecrans, Rubi Lani Sano, Iten Sarabia, Angelo Sawyer, Johnny Shimamura, Kade Shimoda, Deanna Siakkhasone, ayden Silver, Sanjay Slaymaker, Jayden Smith, Kaylub Takei, Leleo Tamuo, Anfin Tanaka, Kain Taulung-Sanford, Tywan Zephaniah Tully, Teagan Watson, Jordyn Wellbrock, Haliaalohaokalikolehua Winder, Tuunerina Yamachika, Dennis Yim, Elijah Yoshikawa, Micah Yoshino, Kaden Zhou, Chengxian (James) Zolezzi Yanez, tefano')]</value>
      <webElementGuid>8f8e5c45-9fa4-44a9-9ba0-36f51bde8d21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
