<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TodayTomorrowThis WeekNext WeekMonda_2ced38</name>
   <tag></tag>
   <elementGuidId>c00642a8-05ef-4136-a1da-5ecbaa3b6ded</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='date_filter_select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#date_filter_select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#date_filter_select</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>402e3646-84f9-44aa-88db-0727c3155e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-stone-700 w-[100%] border-4 p-2</value>
      <webElementGuid>3539106e-c706-4ff7-bb67-99a0d6ab82ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>date_filter_select</value>
      <webElementGuid>1fb9c77d-9d1b-4f81-a4f2-d678d4cb218b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TodayTomorrowThis WeekNext WeekMondayTuesdayWednesdayThursdayFridayNovemberDecemberJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctober</value>
      <webElementGuid>65149544-979f-42fb-9bb7-6ccfb652a4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;date_filter_select&quot;)</value>
      <webElementGuid>cf7af69f-0818-4648-85fc-fe764078f2b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='date_filter_select']</value>
      <webElementGuid>e97e8d0b-1dae-4c15-be84-e19ff8b21bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-wrapper']/select[3]</value>
      <webElementGuid>c7cf14a4-973b-4021-ab51-c06aa83b387b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search...'])[1]/following::select[3]</value>
      <webElementGuid>a496c65f-e242-4cf6-a32f-ab05f52b632a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outer Island'])[1]/following::select[3]</value>
      <webElementGuid>2d271f82-f932-4958-8a6b-0d020af43507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='School'])[1]/preceding::select[3]</value>
      <webElementGuid>4d3cf3b1-8c90-45e2-8f4b-c733c100b4de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student'])[1]/preceding::select[3]</value>
      <webElementGuid>aae59fab-a686-40fb-be92-78503e31faab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[3]</value>
      <webElementGuid>9ec5d35e-2d19-4976-a46f-e95d22b30887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'date_filter_select' and (text() = 'TodayTomorrowThis WeekNext WeekMondayTuesdayWednesdayThursdayFridayNovemberDecemberJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctober' or . = 'TodayTomorrowThis WeekNext WeekMondayTuesdayWednesdayThursdayFridayNovemberDecemberJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctober')]</value>
      <webElementGuid>209162f7-6fbd-4fc4-be1e-f9771400ddbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
