<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All SchoolsAiea ElementaryAiea HighA_ee1d8d</name>
   <tag></tag>
   <elementGuidId>db117465-61b6-409f-8b44-29959044d1f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='school_filter_select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#school_filter_select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#school_filter_select</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>889db771-7b9e-4319-a4f7-3a4294172e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>school_filter_select</value>
      <webElementGuid>bb8aad55-71f4-410b-bb94-90bd2c29bb6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-stone-700 w-[100%] border-4 p-2</value>
      <webElementGuid>b7dd5984-2593-47f7-a09d-22ba6491cdd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All SchoolsAiea ElementaryAiea HighAiea IntermediateBarry SchoolDaniel K. Inouye ElementaryHaleiwaKaala ElementaryKipapa ElementaryLeilehua HighMakalapa ElementaryMililani HighMililani Mauka Elem.Mililani MiddleMililani Uka Elem.Mililani Waena Elem.MoanaluaMoanalua HighMoanalua MiddleNimitz ElementaryPearl Harbor Elem.Radford HighSalt LakeSolomonWahiawa ElementaryWahiawa MiddleWaialuaWaialua High &amp; IntermWebling</value>
      <webElementGuid>40e04249-8d3a-42e4-9f15-bab3bc818149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;school_filter_select&quot;)</value>
      <webElementGuid>2eef456f-ddea-4bc9-9741-a9135df40bff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='school_filter_select']</value>
      <webElementGuid>54af70bc-f0f1-4c2f-b2e9-6c275c649ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-wrapper']/select</value>
      <webElementGuid>3926b3f2-6a1e-4e59-b3ef-8f1a3cb6b558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search...'])[1]/following::select[1]</value>
      <webElementGuid>595b4c31-ca03-4999-86d1-8514c2cbab75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outer Island'])[1]/following::select[1]</value>
      <webElementGuid>75ee4bcf-bdf3-4f9b-80cb-bf14b5c0d913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='School'])[1]/preceding::select[5]</value>
      <webElementGuid>245f777b-f96b-495b-9961-8c06440458ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student'])[1]/preceding::select[5]</value>
      <webElementGuid>3a603a06-6e6b-4bb9-ad63-9b7baa365417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>0f48d895-79ad-4c67-ba70-369e6748b4a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'school_filter_select' and (text() = 'All SchoolsAiea ElementaryAiea HighAiea IntermediateBarry SchoolDaniel K. Inouye ElementaryHaleiwaKaala ElementaryKipapa ElementaryLeilehua HighMakalapa ElementaryMililani HighMililani Mauka Elem.Mililani MiddleMililani Uka Elem.Mililani Waena Elem.MoanaluaMoanalua HighMoanalua MiddleNimitz ElementaryPearl Harbor Elem.Radford HighSalt LakeSolomonWahiawa ElementaryWahiawa MiddleWaialuaWaialua High &amp; IntermWebling' or . = 'All SchoolsAiea ElementaryAiea HighAiea IntermediateBarry SchoolDaniel K. Inouye ElementaryHaleiwaKaala ElementaryKipapa ElementaryLeilehua HighMakalapa ElementaryMililani HighMililani Mauka Elem.Mililani MiddleMililani Uka Elem.Mililani Waena Elem.MoanaluaMoanalua HighMoanalua MiddleNimitz ElementaryPearl Harbor Elem.Radford HighSalt LakeSolomonWahiawa ElementaryWahiawa MiddleWaialuaWaialua High &amp; IntermWebling')]</value>
      <webElementGuid>7a6be28e-4f9d-40ec-b8fe-578572805a3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
