<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All SchoolsAina HainaAliiolani Eleme_ee4a25</name>
   <tag></tag>
   <elementGuidId>d5f9a481-ecd1-47ed-814d-ea55a4f44430</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='school_filter_select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#school_filter_select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#school_filter_select</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>59fe8c43-5f78-4bf9-b151-174e92851bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>school_filter_select</value>
      <webElementGuid>dbde1438-ed23-40fe-9889-f96bc6514fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-stone-700 w-[100%] border-4 p-2</value>
      <webElementGuid>f8e03203-5fdc-4fa4-b5dc-c60f8be7192b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All SchoolsAina HainaAliiolani ElementaryDole MiddleFarrington HighHahaione ElementaryHawaii School for the Deaf &amp; the BlindHokulaniJarrett MiddleKaewai ElementaryKaewai ElementaryKaimuki HighKaimuki MiddleKaiser HighKaiulaniKalakaua MiddleKalani High Kalihi ESKalihi Kai Elem.Kalihi Uka SchoolKalihi Waena Elem.Kamiloiki ElementaryKapalama ElementaryKauluwelaKawananakoa MiddleKeelikolani MiddleKoko Head Elem.Kuhio ElementaryLiholihoLincoln ElementaryLunaliloManoa ElementaryMcKinley HighNiu Valley Middle NoelaniPaloloPuuhale ElementaryQueen Kaahumanu Elem.Roosevelt HighRoyalSTI - CALAMBAStevenson MiddleVoyager Charter SchoolWaikikiWashington MiddleWilson</value>
      <webElementGuid>68e01284-3461-4812-b7d4-bd0a17792432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;school_filter_select&quot;)</value>
      <webElementGuid>96597851-4b55-4df7-b376-91eafd2452fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='school_filter_select']</value>
      <webElementGuid>4162d579-6dab-4b89-95c5-bf7612c26c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-wrapper']/select</value>
      <webElementGuid>b0a6fff0-0b00-40d0-8763-1144d5d19c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search...'])[1]/following::select[1]</value>
      <webElementGuid>2ce2384d-2dc3-4c12-8b6b-aef3ffc4f252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outer Island'])[1]/following::select[1]</value>
      <webElementGuid>3b5f1428-9800-4d3f-98e7-e0977dcf2a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='School'])[1]/preceding::select[5]</value>
      <webElementGuid>11f992f8-de9f-4487-bb29-7049f9ea5e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student'])[1]/preceding::select[5]</value>
      <webElementGuid>8c7f9b51-4d2f-4072-8a34-a80fdd10aa02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4ca5e91a-64bd-48bb-8a90-c31a5833d6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'school_filter_select' and (text() = 'All SchoolsAina HainaAliiolani ElementaryDole MiddleFarrington HighHahaione ElementaryHawaii School for the Deaf &amp; the BlindHokulaniJarrett MiddleKaewai ElementaryKaewai ElementaryKaimuki HighKaimuki MiddleKaiser HighKaiulaniKalakaua MiddleKalani High Kalihi ESKalihi Kai Elem.Kalihi Uka SchoolKalihi Waena Elem.Kamiloiki ElementaryKapalama ElementaryKauluwelaKawananakoa MiddleKeelikolani MiddleKoko Head Elem.Kuhio ElementaryLiholihoLincoln ElementaryLunaliloManoa ElementaryMcKinley HighNiu Valley Middle NoelaniPaloloPuuhale ElementaryQueen Kaahumanu Elem.Roosevelt HighRoyalSTI - CALAMBAStevenson MiddleVoyager Charter SchoolWaikikiWashington MiddleWilson' or . = 'All SchoolsAina HainaAliiolani ElementaryDole MiddleFarrington HighHahaione ElementaryHawaii School for the Deaf &amp; the BlindHokulaniJarrett MiddleKaewai ElementaryKaewai ElementaryKaimuki HighKaimuki MiddleKaiser HighKaiulaniKalakaua MiddleKalani High Kalihi ESKalihi Kai Elem.Kalihi Uka SchoolKalihi Waena Elem.Kamiloiki ElementaryKapalama ElementaryKauluwelaKawananakoa MiddleKeelikolani MiddleKoko Head Elem.Kuhio ElementaryLiholihoLincoln ElementaryLunaliloManoa ElementaryMcKinley HighNiu Valley Middle NoelaniPaloloPuuhale ElementaryQueen Kaahumanu Elem.Roosevelt HighRoyalSTI - CALAMBAStevenson MiddleVoyager Charter SchoolWaikikiWashington MiddleWilson')]</value>
      <webElementGuid>ce669cda-0c06-46ab-910d-1708ce0f3205</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
