<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All Students Baldonado, Isaac Ballar_21582d</name>
   <tag></tag>
   <elementGuidId>f341bdc3-4e34-4ff8-88a6-8a8bf9d17748</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='student_filter_select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#student_filter_select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#student_filter_select</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6625b885-fe1e-404b-be91-dcfe04c5a204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>student_filter_select</value>
      <webElementGuid>cd6e9ec6-4c73-484e-b4ca-f1aa0f0dcda8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-stone-700 w-[100%] border-4 p-2</value>
      <webElementGuid>e3f82a80-89bf-4113-a3fd-f0c4c3e36309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Students Baldonado, Isaac Ballard, Antonio Bell, Sophie Billedo, Shylee Billena, Kian Bjorn, Tove Brandley, Demetrius Brown, Elara Brub, Jordan Cadiz, James David Dale, Adalynn Edayan, Marco Espinosa, Zaynein Faust, DaRiyah Fujinaga, Chenoa Furumoto, Kiryn Galiki, Joseph Gerard, Hunter Geronimo, Rhamxie Gene Gomes, Sierra Guarino, Marc Anthony Haddad, Gabriel Hanson, Max Higa, Avery Hirota, Kiri Horibata, Aiden Kaeha-Lumaban, Kiara-Zailey Kaiwi, ilinahe Kamihara, Joseph Kaneali'i-Gonsalves, Keonalani Kuehu, Nalani Lin, Kelly Lorin, Roxanda Manu, Isaiah A Marcelin, Kenya Martin, Oryan Masden, Aspen Matsumoto, Nora McGoldrick, Mason McLean, Aaliyah Nabatilan, Skye Oden, Stanley Osborne, Skyler Pene, ardy Perry, Colton Pinedo, Noah Quast, Ari Reyes, Amonie Rivera-Feleti, David Savea, Seilagi Seino, Haven Shibasaki, Scarlett Shiroma, Kyler Silva-Kaalekahi, Kainalu Soriano, Rachel Suli, Kaleo Tavai, Taimane Teriipaia-Loo, Merahi Tolentino, Skylar Tollefsen, Reign Trotter, Lily Tsujiguchi, Mason Tuaau Sesepasara, Purinesese Ursua De Rego, Kahiau Viloria, Kyra Waddell, Anela-Hope Watson, Olive Williams, Kyrielle Yanagihara, Bailey</value>
      <webElementGuid>f56ca04a-c447-473d-a961-b1c8411c78d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;student_filter_select&quot;)</value>
      <webElementGuid>b2aad494-27db-41df-9693-093566d406d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='student_filter_select']</value>
      <webElementGuid>8cc3652a-f83a-420a-a3cc-f3db26930196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-wrapper']/select[2]</value>
      <webElementGuid>1b9428a1-74a9-45da-b095-43902b6ea1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search...'])[1]/following::select[2]</value>
      <webElementGuid>d7a3392d-4593-44aa-ab1f-f7e3eb7c73b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outer Island'])[1]/following::select[2]</value>
      <webElementGuid>15ecedf0-ecc8-423a-8945-4c26f8fbac93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='School'])[1]/preceding::select[4]</value>
      <webElementGuid>1e856455-da68-424f-958f-85b571c8609e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student'])[1]/preceding::select[4]</value>
      <webElementGuid>4e7076c3-9840-4ec0-8efc-b50fb24500a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>aa3c6053-d3a8-4c02-8978-a7f1b2f5026a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'student_filter_select' and (text() = concat(&quot;All Students Baldonado, Isaac Ballard, Antonio Bell, Sophie Billedo, Shylee Billena, Kian Bjorn, Tove Brandley, Demetrius Brown, Elara Brub, Jordan Cadiz, James David Dale, Adalynn Edayan, Marco Espinosa, Zaynein Faust, DaRiyah Fujinaga, Chenoa Furumoto, Kiryn Galiki, Joseph Gerard, Hunter Geronimo, Rhamxie Gene Gomes, Sierra Guarino, Marc Anthony Haddad, Gabriel Hanson, Max Higa, Avery Hirota, Kiri Horibata, Aiden Kaeha-Lumaban, Kiara-Zailey Kaiwi, ilinahe Kamihara, Joseph Kaneali&quot; , &quot;'&quot; , &quot;i-Gonsalves, Keonalani Kuehu, Nalani Lin, Kelly Lorin, Roxanda Manu, Isaiah A Marcelin, Kenya Martin, Oryan Masden, Aspen Matsumoto, Nora McGoldrick, Mason McLean, Aaliyah Nabatilan, Skye Oden, Stanley Osborne, Skyler Pene, ardy Perry, Colton Pinedo, Noah Quast, Ari Reyes, Amonie Rivera-Feleti, David Savea, Seilagi Seino, Haven Shibasaki, Scarlett Shiroma, Kyler Silva-Kaalekahi, Kainalu Soriano, Rachel Suli, Kaleo Tavai, Taimane Teriipaia-Loo, Merahi Tolentino, Skylar Tollefsen, Reign Trotter, Lily Tsujiguchi, Mason Tuaau Sesepasara, Purinesese Ursua De Rego, Kahiau Viloria, Kyra Waddell, Anela-Hope Watson, Olive Williams, Kyrielle Yanagihara, Bailey&quot;) or . = concat(&quot;All Students Baldonado, Isaac Ballard, Antonio Bell, Sophie Billedo, Shylee Billena, Kian Bjorn, Tove Brandley, Demetrius Brown, Elara Brub, Jordan Cadiz, James David Dale, Adalynn Edayan, Marco Espinosa, Zaynein Faust, DaRiyah Fujinaga, Chenoa Furumoto, Kiryn Galiki, Joseph Gerard, Hunter Geronimo, Rhamxie Gene Gomes, Sierra Guarino, Marc Anthony Haddad, Gabriel Hanson, Max Higa, Avery Hirota, Kiri Horibata, Aiden Kaeha-Lumaban, Kiara-Zailey Kaiwi, ilinahe Kamihara, Joseph Kaneali&quot; , &quot;'&quot; , &quot;i-Gonsalves, Keonalani Kuehu, Nalani Lin, Kelly Lorin, Roxanda Manu, Isaiah A Marcelin, Kenya Martin, Oryan Masden, Aspen Matsumoto, Nora McGoldrick, Mason McLean, Aaliyah Nabatilan, Skye Oden, Stanley Osborne, Skyler Pene, ardy Perry, Colton Pinedo, Noah Quast, Ari Reyes, Amonie Rivera-Feleti, David Savea, Seilagi Seino, Haven Shibasaki, Scarlett Shiroma, Kyler Silva-Kaalekahi, Kainalu Soriano, Rachel Suli, Kaleo Tavai, Taimane Teriipaia-Loo, Merahi Tolentino, Skylar Tollefsen, Reign Trotter, Lily Tsujiguchi, Mason Tuaau Sesepasara, Purinesese Ursua De Rego, Kahiau Viloria, Kyra Waddell, Anela-Hope Watson, Olive Williams, Kyrielle Yanagihara, Bailey&quot;))]</value>
      <webElementGuid>23ff9224-28b6-45ed-81e9-3399c5563be3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
