<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Send another request to my Microsoft Auth_2dd237</name>
   <tag></tag>
   <elementGuidId>53fe6e96-f140-4c0a-a712-068657e4dc4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='idA_SAASDS_Resend']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idA_SAASDS_Resend</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Send another request to my Microsoft Authenticator app&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e164591b-eea6-4207-b335-19a0b43b78de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c640ed0a-a60c-4f35-92ec-7b622641c58f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>html: resendText, attr: { id: getId('idA', 'Resend') }, click: resend_onClick</value>
      <webElementGuid>bdd5c497-7cfe-448b-8a48-fee80e0d8234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idA_SAASDS_Resend</value>
      <webElementGuid>aa66b77c-61df-4892-a596-51b40980a00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send another request to my Microsoft Authenticator app</value>
      <webElementGuid>71b695a4-a0f1-46de-91e4-6a18f4fe866d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idA_SAASDS_Resend&quot;)</value>
      <webElementGuid>d1e812cb-92c8-4f87-8f6d-5561902577de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='idA_SAASDS_Resend']</value>
      <webElementGuid>f85d2f79-3099-4acb-bfa3-6e7958bba82f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lightbox']/div[2]/div[2]/div/div[2]/div/div/div[3]/a</value>
      <webElementGuid>5f0591bc-5c42-4883-aa6b-07619c346b11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Send another request to my Microsoft Authenticator app')]</value>
      <webElementGuid>73b9b215-6447-4139-832b-8d04bc310dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We sent an identity verification request to your mobile device, but you denied it.'])[1]/following::a[2]</value>
      <webElementGuid>543e1498-d6d2-4cc5-b235-6c64aff10f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Having trouble?'])[1]/preceding::a[1]</value>
      <webElementGuid>a7a25295-8b16-4899-a8d8-9c5a1d4d68a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send another request to my Microsoft Authenticator app']/parent::*</value>
      <webElementGuid>785b1fa9-560e-4fee-b22f-4fe76bd462a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>70785a97-5d21-4ae9-81e7-2c5516a2bd87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>ff3284eb-7913-4b9a-b008-df8636c7699f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'idA_SAASDS_Resend' and (text() = 'Send another request to my Microsoft Authenticator app' or . = 'Send another request to my Microsoft Authenticator app')]</value>
      <webElementGuid>459c37c8-ff56-4c26-94f5-5384df2af1e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
