<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign in_lightbox-cover</name>
   <tag></tag>
   <elementGuidId>d8e1044e-9142-43fa-a577-15ef12e4ba6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.lightbox-cover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='lightbox']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.lightbox-cover</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>deeed66d-8824-4448-adfd-ad524e9a07aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lightbox-cover</value>
      <webElementGuid>e4e7f94e-cc29-4a46-8ae4-69d4dd252a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>css: { 'disable-lightbox': svr.fAllowGrayOutLightBox &amp;&amp; showLightboxProgress() }</value>
      <webElementGuid>bdd31734-ca8e-4b33-80d7-8e8741102422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lightbox&quot;)/div[@class=&quot;lightbox-cover&quot;]</value>
      <webElementGuid>50a6b761-91d1-44f9-8b17-9d49036f32fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lightbox']/div</value>
      <webElementGuid>7453a19b-269f-4828-8f8d-06d3a47b427c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div</value>
      <webElementGuid>7f6f3e5e-b1e9-4270-a535-e2ced998c944</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
