<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Thu</name>
   <tag></tag>
   <elementGuidId>bdb93eb5-2c7f-4080-bd08-c8dca6125e62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='col_5_dayname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#col_5_dayname</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Thu&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>109f8216-7d69-4559-8666-fd9264026171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>col_5_dayname</value>
      <webElementGuid>6623f074-5572-4f5a-911e-1fe371f207a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thu</value>
      <webElementGuid>fcd60493-889a-4ed6-bec1-f1da2f0c012f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;col_5_dayname&quot;)</value>
      <webElementGuid>c7fecee4-f83e-46fc-95ed-8ce122dd5889</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='col_5_dayname']</value>
      <webElementGuid>ef7febc6-5f09-4ddc-8069-ccc0d49d2c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='horizontal_col_5 day_name']/p</value>
      <webElementGuid>b2b60850-8b14-45c9-a2ee-cd4f8678c461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student / School'])[1]/following::p[7]</value>
      <webElementGuid>0d3d8e64-dfa4-422a-b707-17420c93f627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search...'])[1]/following::p[7]</value>
      <webElementGuid>2642680d-e145-4aa9-a3d6-48b72de3ee1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aina Haina'])[2]/preceding::p[4]</value>
      <webElementGuid>0bbe4366-4be7-408a-a345-0438ec54a11c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thu']/parent::*</value>
      <webElementGuid>ee92f8c2-2142-48fc-ad3b-ca1babefdb2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[5]/span/div/p</value>
      <webElementGuid>09b5b8e8-36cd-4aff-8cbf-7e7ca69b45fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'col_5_dayname' and (text() = 'Thu' or . = 'Thu')]</value>
      <webElementGuid>28e59fbc-b9e6-4eaf-b924-d5d0d131fa74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
