<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Aguirre, Lucia</name>
   <tag></tag>
   <elementGuidId>73d30728-03cb-44bb-a6e7-4106387e9381</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='providerlist6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#providerlist6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Aguirre, Lucia&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>051120c4-5d13-4503-a1b9-156cebe51d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer hover:bg-gray-200</value>
      <webElementGuid>6e32581d-4d90-40aa-88ba-c60086c14e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>providerlist6</value>
      <webElementGuid>b97f582e-593c-44a0-96a8-07ec6244a96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aguirre, Lucia</value>
      <webElementGuid>a01a3051-f620-46ef-af9c-b95ddef79b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;providerlist6&quot;)</value>
      <webElementGuid>5a6da51a-80ec-4644-9095-46458e9022f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='providerlist6']</value>
      <webElementGuid>31096e18-c0c9-451f-bd4b-accc1c65abcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/dialog/div[2]/div/div[2]/h2[7]</value>
      <webElementGuid>4813090c-fb69-4c57-bfaf-c3f9ec169fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aguirre']/parent::*</value>
      <webElementGuid>ed120df8-454b-4011-aa92-1dc4001332a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2[7]</value>
      <webElementGuid>397f467c-5d9b-47bb-b2c1-bdb84ea98114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'providerlist6' and (text() = 'Aguirre, Lucia' or . = 'Aguirre, Lucia')]</value>
      <webElementGuid>58294b8a-e738-47df-8ceb-5f5217d6d650</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
