<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All Students Abe, Tyler Avilla, Linc_0e3850</name>
   <tag></tag>
   <elementGuidId>4d6d246e-824e-461c-9899-cb9daf922a1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='student_filter_select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#student_filter_select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#student_filter_select</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d5cb37d4-c92c-4df6-b339-e56c3f1ac644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>student_filter_select</value>
      <webElementGuid>2607d945-e8bf-43ce-a8b7-4249e69dc357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-stone-700 w-[100%] border-4 p-2</value>
      <webElementGuid>d2ea4d68-82c1-418b-97e1-31e0a59a5470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Students Abe, Tyler Avilla, Lincoln Borja, Kylcer Bronson, Ari Caleb, Helio Choy, Kaylie Danielson, Isaiah Dela Cruz, Channelohan Dinius, Kara Diza, Kyzen Dobrescu, Alexandra Fujiyama, Dayneka Fukuda, Ellen Hahn, Marlee Hallers, Frandawn Haluber, Melissa Harrell, Keahi Hashemi, Jasmin Hiraishi, Wynn Hopkins, Weston Ichikawa, Sen Jay-Funaki, Nya Koiten, Kayshawn Koki, kye Kunz Martin, Cataleya Jade Labuguen, Diani Lambot, Immanuel Langidrik, Daisey Ledo Glade, Paloma Lee, Kristian Machado, Ronnie Mate, Izabelle Mcelfresh, Helixorion Mowatt, Scott Mwangin, D-Hearth Nakamura, Ren Nguyen, Khai Nicholas, Duke Nobleza, Jacob Olive, Oriana Orosco Thomas, Akayla Palacpac, Jumar Pang, Josiah Panganiban, Mila Pepper, Nazca Pineda, Ysabelle Ramos, Jayzen Renny, Ersalyn Rof, Rdsapino Rosecrans, Rubi Lani Sano, Iten Sarabia, Angelo Sawyer, Johnny Shimamura, Kade Shimoda, Deanna Silver, Sanjay Slaymaker, Jayden Smith, Kaylub Takei, Leleo Tamuo, Anfin Tanaka, Kain Taulung-Sanford, Tywan Zephaniah Tully, Teagan Watson, Jordyn Wellbrock, Haliaalohaokalikolehua Winder, Tuunerina Yamachika, Dennis Yim, Elijah Yoshikawa, Micah Yoshino, Kaden Zhou, Chengxian (James)</value>
      <webElementGuid>bbd38fdb-1aef-4019-b249-25db7b274f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;student_filter_select&quot;)</value>
      <webElementGuid>840d0db8-685f-4687-98aa-8944bfb85c2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='student_filter_select']</value>
      <webElementGuid>da6149cc-0ca6-4a96-acd3-9abc60210161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-wrapper']/select[2]</value>
      <webElementGuid>581425db-395c-4e94-a6b7-2573b4085588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search...'])[1]/following::select[2]</value>
      <webElementGuid>663a51c9-454c-4ca8-b4ac-58f580dec0ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outer Island'])[1]/following::select[2]</value>
      <webElementGuid>a29cf2a2-b98b-4ece-975d-a15cfeb18646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='School'])[1]/preceding::select[4]</value>
      <webElementGuid>9766c5aa-57fb-42c2-8665-2d416c0dabcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student'])[1]/preceding::select[4]</value>
      <webElementGuid>96794d92-76dd-4dbb-9329-9e1d06a76ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>bb7e517b-baac-4101-803e-9cdadb5891dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'student_filter_select' and (text() = 'All Students Abe, Tyler Avilla, Lincoln Borja, Kylcer Bronson, Ari Caleb, Helio Choy, Kaylie Danielson, Isaiah Dela Cruz, Channelohan Dinius, Kara Diza, Kyzen Dobrescu, Alexandra Fujiyama, Dayneka Fukuda, Ellen Hahn, Marlee Hallers, Frandawn Haluber, Melissa Harrell, Keahi Hashemi, Jasmin Hiraishi, Wynn Hopkins, Weston Ichikawa, Sen Jay-Funaki, Nya Koiten, Kayshawn Koki, kye Kunz Martin, Cataleya Jade Labuguen, Diani Lambot, Immanuel Langidrik, Daisey Ledo Glade, Paloma Lee, Kristian Machado, Ronnie Mate, Izabelle Mcelfresh, Helixorion Mowatt, Scott Mwangin, D-Hearth Nakamura, Ren Nguyen, Khai Nicholas, Duke Nobleza, Jacob Olive, Oriana Orosco Thomas, Akayla Palacpac, Jumar Pang, Josiah Panganiban, Mila Pepper, Nazca Pineda, Ysabelle Ramos, Jayzen Renny, Ersalyn Rof, Rdsapino Rosecrans, Rubi Lani Sano, Iten Sarabia, Angelo Sawyer, Johnny Shimamura, Kade Shimoda, Deanna Silver, Sanjay Slaymaker, Jayden Smith, Kaylub Takei, Leleo Tamuo, Anfin Tanaka, Kain Taulung-Sanford, Tywan Zephaniah Tully, Teagan Watson, Jordyn Wellbrock, Haliaalohaokalikolehua Winder, Tuunerina Yamachika, Dennis Yim, Elijah Yoshikawa, Micah Yoshino, Kaden Zhou, Chengxian (James)' or . = 'All Students Abe, Tyler Avilla, Lincoln Borja, Kylcer Bronson, Ari Caleb, Helio Choy, Kaylie Danielson, Isaiah Dela Cruz, Channelohan Dinius, Kara Diza, Kyzen Dobrescu, Alexandra Fujiyama, Dayneka Fukuda, Ellen Hahn, Marlee Hallers, Frandawn Haluber, Melissa Harrell, Keahi Hashemi, Jasmin Hiraishi, Wynn Hopkins, Weston Ichikawa, Sen Jay-Funaki, Nya Koiten, Kayshawn Koki, kye Kunz Martin, Cataleya Jade Labuguen, Diani Lambot, Immanuel Langidrik, Daisey Ledo Glade, Paloma Lee, Kristian Machado, Ronnie Mate, Izabelle Mcelfresh, Helixorion Mowatt, Scott Mwangin, D-Hearth Nakamura, Ren Nguyen, Khai Nicholas, Duke Nobleza, Jacob Olive, Oriana Orosco Thomas, Akayla Palacpac, Jumar Pang, Josiah Panganiban, Mila Pepper, Nazca Pineda, Ysabelle Ramos, Jayzen Renny, Ersalyn Rof, Rdsapino Rosecrans, Rubi Lani Sano, Iten Sarabia, Angelo Sawyer, Johnny Shimamura, Kade Shimoda, Deanna Silver, Sanjay Slaymaker, Jayden Smith, Kaylub Takei, Leleo Tamuo, Anfin Tanaka, Kain Taulung-Sanford, Tywan Zephaniah Tully, Teagan Watson, Jordyn Wellbrock, Haliaalohaokalikolehua Winder, Tuunerina Yamachika, Dennis Yim, Elijah Yoshikawa, Micah Yoshino, Kaden Zhou, Chengxian (James)')]</value>
      <webElementGuid>239bc25f-6e3c-4ba0-9942-6575e3fa7c8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
