<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TodayTomorrowThis WeekNext WeekOctob_108650</name>
   <tag></tag>
   <elementGuidId>c2bed069-6eb7-44ef-952c-198997cf8bb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='date_filter_select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#date_filter_select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#date_filter_select</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f5e9fc05-a6cc-412a-a987-d4b984d34155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-stone-700 w-[100%] border-4 p-2</value>
      <webElementGuid>e7123576-be03-42ed-8adc-111b5c1197fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>date_filter_select</value>
      <webElementGuid>36e27ca7-6884-4418-84c7-d49ba14b43d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TodayTomorrowThis WeekNext WeekOctoberNovemberDecemberJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptember</value>
      <webElementGuid>8a97ea8c-e10f-4c28-8e83-f29fedc1e13a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;date_filter_select&quot;)</value>
      <webElementGuid>9007da03-3ce4-4b8f-b2b0-8d3d1e35b358</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='date_filter_select']</value>
      <webElementGuid>d768c7bc-1a6c-446f-a2d0-85609a7bbed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-wrapper']/select[3]</value>
      <webElementGuid>19c901b3-e115-4cec-9695-47ad873ca18a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search...'])[1]/following::select[3]</value>
      <webElementGuid>acdef5a5-d903-4d08-af3f-9468bfadd781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outer Island'])[1]/following::select[3]</value>
      <webElementGuid>96e7cf9b-6a3c-44ba-8c43-6972cd201c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='School'])[1]/preceding::select[3]</value>
      <webElementGuid>74dbccf9-ba93-4a50-b735-da1b8d5e6cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student'])[1]/preceding::select[3]</value>
      <webElementGuid>598bf68f-818e-45dc-954a-cacb8f22e987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[3]</value>
      <webElementGuid>3fb83737-8a7d-42dd-81f8-06401a816796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'date_filter_select' and (text() = 'TodayTomorrowThis WeekNext WeekOctoberNovemberDecemberJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptember' or . = 'TodayTomorrowThis WeekNext WeekOctoberNovemberDecemberJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptember')]</value>
      <webElementGuid>a06b7307-60b4-4e9a-8568-a696d36d3533</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
