<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tue, 1015 1415 - 1730_master-checkbox_b03bcc</name>
   <tag></tag>
   <elementGuidId>dee35861-2a93-4275-8ab1-b05338f2939f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='master-checkbox-toggle159407']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#master-checkbox-toggle159407</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#master-checkbox-toggle159407</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4ea94f7-727b-4c02-a591-0d963e6038ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>master-checkbox-toggle159407</value>
      <webElementGuid>cfe5cc48-a579-41ff-9e86-3f9a5a90f2d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6739359b-d251-41fd-8296-f64069364518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;master-checkbox-toggle159407&quot;)</value>
      <webElementGuid>05b3182c-de85-4bf0-88d1-d673fd1b3792</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='master-checkbox-toggle159407']</value>
      <webElementGuid>e8baeed2-b248-4a16-be15-3eae0dc2e1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr-main-14']/td[4]/div/input</value>
      <webElementGuid>2241ba4b-6bfa-4f67-a66e-077e721cc37b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[16]/td[4]/div/input</value>
      <webElementGuid>09f93758-5808-4bd2-ae85-49f1d8140680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'master-checkbox-toggle159407' and @type = 'checkbox']</value>
      <webElementGuid>a592f3e8-654c-4312-b9e8-d55622b9424d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
