<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fri, 1011 0800 - 1415_master-checkbox_b4dbbf</name>
   <tag></tag>
   <elementGuidId>6f2a9ed3-8535-41f8-a9b6-9d61da4a4bd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='master-checkbox-toggle160304']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#master-checkbox-toggle160304</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#master-checkbox-toggle160304</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a9576e4-5325-4da9-a64c-01740abeaf5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>master-checkbox-toggle160304</value>
      <webElementGuid>6404c3f6-b1e7-4e87-b42e-d5b9c20ab35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>91cdea95-69c9-4bd3-8128-6edbddafe0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;master-checkbox-toggle160304&quot;)</value>
      <webElementGuid>e39c0fc6-a59b-4a4a-af1d-2990047b8712</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id=master-checkbox-toggle164248']</value>
      <webElementGuid>73b0fccf-e13d-4864-8e5f-6cb561cf6572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr-main-1']/td[4]/div/input</value>
      <webElementGuid>535c00a2-6f28-4d45-8cc5-6ad2cc2f5c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/div/input</value>
      <webElementGuid>349be3f4-c0be-45a8-a64b-cf768ffc5eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'master-checkbox-toggle160304' and @type = 'checkbox']</value>
      <webElementGuid>315dcaa7-31f0-41bf-915b-2bb5defcd681</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
