<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mon, 1014 0730 - 1330_master-checkbox_a6df69</name>
   <tag></tag>
   <elementGuidId>78fea10b-c896-4fd3-98d0-80fcad254807</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#master-checkbox-toggle168145</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='master-checkbox-toggle168145']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#master-checkbox-toggle168145</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0854e19-f639-4ea5-a527-e7781efff9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>master-checkbox-toggle168145</value>
      <webElementGuid>d76f199d-16c7-4d1b-b6d4-029a876c9af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4a084fd1-cb84-43cd-9a2b-c27997dffa53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;master-checkbox-toggle168145&quot;)</value>
      <webElementGuid>ebaa0a2c-0a1f-47cd-939e-6681c48effba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='master-checkbox-toggle168145']</value>
      <webElementGuid>3648dcc4-baec-4146-8673-1b51b0c66422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr-main-4']/td[4]/div/input</value>
      <webElementGuid>730fe473-7836-4572-9ac7-c650868529a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[4]/div/input</value>
      <webElementGuid>f4fa8fea-c9e4-4386-93f9-938c3e444b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'master-checkbox-toggle168145' and @type = 'checkbox']</value>
      <webElementGuid>30b2ff6c-3725-4d4a-ade0-56e34d44e429</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
