<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tue, 1015 0730 - 1415_master-checkbox_676fcd</name>
   <tag></tag>
   <elementGuidId>87dc1d6d-9750-4631-a4c6-e9f17f5a95c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='master-checkbox-toggle165250']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#master-checkbox-toggle165250</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#master-checkbox-toggle165250</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fec481c2-d5cd-4fa4-b60f-9cdd6a8cfe62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>master-checkbox-toggle165250</value>
      <webElementGuid>22c3d68e-fde6-4e48-a4e3-0617c8f48762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>85058605-b60f-4f33-b8a6-23afd00805a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;master-checkbox-toggle165250&quot;)</value>
      <webElementGuid>46c5f0ab-2f6e-44f3-a60a-9cf14e894f32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='master-checkbox-toggle165250']</value>
      <webElementGuid>fdfdc6ce-8369-4468-a37c-da3c9aa56227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr-main-12']/td[4]/div/input</value>
      <webElementGuid>25f2fc38-a0e7-4cad-b545-febfa3513721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td[4]/div/input</value>
      <webElementGuid>b88a2f39-2e34-456a-8db7-f35fe724ba38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'master-checkbox-toggle165250' and @type = 'checkbox']</value>
      <webElementGuid>f1414a78-7e95-48b4-ab22-24db6ed3c11f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
