<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tue, 1015 0800 - 1415_master-checkbox_1dd056</name>
   <tag></tag>
   <elementGuidId>f1df4fe9-81f0-4207-a96c-0a0ca6f41b23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='master-checkbox-toggle164810']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#master-checkbox-toggle164810</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#master-checkbox-toggle164810</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3928d58d-5a29-4b50-85dd-f8a70e3605de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>master-checkbox-toggle164810</value>
      <webElementGuid>2166dcb4-0912-4f17-acdf-a40e2f076938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5831b9cc-da44-4b2e-b7d1-d009089ba92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;master-checkbox-toggle164810&quot;)</value>
      <webElementGuid>4f7f712a-0060-4b32-8a75-9be5b05a8c20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='master-checkbox-toggle164810']</value>
      <webElementGuid>71017da3-1d9a-401a-9028-c1ce612094e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr-main-0']/td[4]/div/input</value>
      <webElementGuid>72e41435-10cb-45e1-9461-dabfce6b71c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/input</value>
      <webElementGuid>979f23d6-cb4d-4332-ae83-bdebe822fc02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'master-checkbox-toggle164810' and @type = 'checkbox']</value>
      <webElementGuid>9f528da5-e8e1-48b6-be92-f6e5541a1b84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
