<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1</name>
   <tag></tag>
   <elementGuidId>ae4c9e71-ac53-4b55-89f6-d5046f432421</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[title=&quot;#D0E3F4&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='color-picker-holder']/div[2]/div[2]/div/span[4]/div/span/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;#D0E3F4&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6c01be36-4c86-4360-8473-29c6009df91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>#D0E3F4</value>
      <webElementGuid>ebccbcc8-495b-4c03-bb8a-5f8e46ca81f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>49e29090-e650-4323-a430-09a3449e70bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;color-picker-holder&quot;)/div[@class=&quot;relative mb-2 ml-4 flex items-center&quot;]/div[@class=&quot;absolute z-50 mt-2 rounded-lg p-2&quot;]/div[@class=&quot;github-picker custom-twitter-picker&quot;]/span[4]/div[1]/span[1]/div[1]</value>
      <webElementGuid>63ec6aa0-a022-4539-ae2f-cb59787b13d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='color-picker-holder']/div[2]/div[2]/div/span[4]/div/span/div</value>
      <webElementGuid>7d7f4b98-8249-415f-833d-b22987be73b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/div/span/div</value>
      <webElementGuid>380855b4-5be6-49fc-9416-9d9efe66fdc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = '#D0E3F4']</value>
      <webElementGuid>2133311b-2eb8-489a-b845-cf6a48513794</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
