<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_OPEN</name>
   <tag></tag>
   <elementGuidId>e0d15eb4-32f8-42b6-b787-af24876d6d8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='tr-main-1']/td[2]/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tr-main-1 >> internal:text=&quot;OPEN&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>31743e4f-5f8d-44f7-a129-30c1759c7f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OPEN</value>
      <webElementGuid>26249bf5-5feb-4735-b018-297a5f837b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tr-main-1&quot;)/td[@class=&quot;border-2 border-gray-200 align-middle w-[3em]&quot;]/div[1]/div[@class=&quot;relative h-full min-h-4 cursor-pointer text-center align-middle hover:brightness-[1.05] bg-yellow-400 text-red-600 font-semibold p-2&quot;]/p[1]</value>
      <webElementGuid>79427cfd-c87d-4eb7-acbd-8295a7be6dbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr-main-1']/td[2]/div/div/p</value>
      <webElementGuid>7f7fb3d8-5051-49e1-8c36-d8f465d6527a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Castle High School'])[4]/following::p[1]</value>
      <webElementGuid>261bafcc-7939-4a68-a8f5-2aa860a08238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Castle High School'])[5]/preceding::p[10]</value>
      <webElementGuid>e02f6009-7245-4444-a471-1332d0d4c1a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/p</value>
      <webElementGuid>8902930b-cdcc-40b5-8e29-5d1a97587e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'OPEN' or . = 'OPEN')]</value>
      <webElementGuid>6844176a-68e4-465f-b294-68bed711dd0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
