<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>date_filter</name>
   <tag></tag>
   <elementGuidId>94c51eac-d71f-4f75-8db1-39a33e07c09b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='date_filter_select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#date_filter_select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#date_filter_select</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e0786b06-979d-4321-914e-ece34e31eeff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-stone-700 w-[100%] border-4 p-2</value>
      <webElementGuid>c31accbe-8c74-4c94-9ad2-a2f5cecde069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>date_filter_select</value>
      <webElementGuid>01b3afb0-e7ed-4549-bbf4-efcf0e85d432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TodayTomorrowThis WeekNext WeekOctoberNovemberDecemberJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptember</value>
      <webElementGuid>06e75de0-0cbc-4f9f-a5a9-2a28002d8e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;date_filter_select&quot;)</value>
      <webElementGuid>92cbd824-d885-4588-bfe0-027f0b2f6c9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='date_filter_select']</value>
      <webElementGuid>434e1d52-b98c-4c9b-9bd5-c284c712b1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-wrapper']/select[3]</value>
      <webElementGuid>9e9996ef-6f4f-4bde-9cd3-86892c104322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search...'])[1]/following::select[3]</value>
      <webElementGuid>cc98d623-fbcf-4960-b684-a56cba4a8fe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outer Island'])[1]/following::select[3]</value>
      <webElementGuid>d1603529-754d-482c-8ede-5c81a69b7398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='School'])[1]/preceding::select[3]</value>
      <webElementGuid>21cdfc15-0257-4e24-ac5c-c9bf32a259d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student'])[1]/preceding::select[3]</value>
      <webElementGuid>8ad7b8dd-c1f3-49cb-b4f0-89628701c702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[3]</value>
      <webElementGuid>a425a81a-3512-4bfe-8703-a54931c74365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'date_filter_select' and (text() = 'TodayTomorrowThis WeekNext WeekOctoberNovemberDecemberJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptember' or . = 'TodayTomorrowThis WeekNext WeekOctoberNovemberDecemberJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptember')]</value>
      <webElementGuid>5fff9650-6a7d-4604-a8f3-afe9cada84c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
