<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TodayTomorrowThis WeekNext WeekMonda_2ced38</name>
   <tag></tag>
   <elementGuidId>cd2840a7-f087-4d06-8ce4-7398adedc645</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='date_filter_select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#date_filter_select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#date_filter_select</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a5b1433b-0081-4eb7-bbc7-941ca2245f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-stone-700 w-[100%] border-4 p-2</value>
      <webElementGuid>f6957ace-6252-4dac-9c61-b9c60fbc923a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>date_filter_select</value>
      <webElementGuid>195ec063-3936-4395-9479-4686431784c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TodayTomorrowThis WeekNext WeekMondayTuesdayWednesdayThursdayFridayNovemberDecemberJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctober</value>
      <webElementGuid>13116a43-5ad3-4586-ba36-6efeaea82c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;date_filter_select&quot;)</value>
      <webElementGuid>4b99ec9e-3b38-4c3a-86cb-e177597add5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='date_filter_select']</value>
      <webElementGuid>68bd4b8c-504a-4e3a-8c1f-fa32d9565164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-wrapper']/select[3]</value>
      <webElementGuid>4c557bae-6257-4673-8e69-b985388f1f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search...'])[1]/following::select[3]</value>
      <webElementGuid>5a1c95fc-5420-4c59-96aa-6e8f22bcf5ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kauai'])[1]/following::select[3]</value>
      <webElementGuid>ea106319-da2a-46a6-a8ba-5906ab15cf45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='School'])[1]/preceding::select[3]</value>
      <webElementGuid>6a00b8d7-cb33-499e-9220-fcbd0ddd49f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student'])[1]/preceding::select[3]</value>
      <webElementGuid>2931f4c2-1140-462d-961d-a25ff6fac17b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[3]</value>
      <webElementGuid>b8a23bd5-01d6-4703-8ca0-ff55024d48f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'date_filter_select' and (text() = 'TodayTomorrowThis WeekNext WeekMondayTuesdayWednesdayThursdayFridayNovemberDecemberJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctober' or . = 'TodayTomorrowThis WeekNext WeekMondayTuesdayWednesdayThursdayFridayNovemberDecemberJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctober')]</value>
      <webElementGuid>d867b918-d5f8-4d2f-975d-d45e2276351f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
