<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All SchoolsABCABCAina HainaAliiolani_54180c</name>
   <tag></tag>
   <elementGuidId>8f6a8787-8745-4c31-a586-1a5799f6e20a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='school_filter_select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#school_filter_select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#school_filter_select</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>07bb6dfd-0f3a-4683-9fbb-2831705884a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>school_filter_select</value>
      <webElementGuid>16fdf251-0098-460e-8055-2b7257b393a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-stone-700 w-[100%] border-4 p-2</value>
      <webElementGuid>7303f2d7-68ec-40c3-98ee-a87a5c0a92aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All SchoolsABCABCAina HainaAliiolani ElementaryDole MiddleFarrington HighHahaione ElementaryHokulaniJarrett MiddleKaewai ElementaryKaewai ElementaryKaimuki HighKaimuki MiddleKaiser HighKaiulaniKalakaua MiddleKalani High Kalihi ESKalihi Kai Elem.Kalihi Uka SchoolKalihi Waena Elem.Kamiloiki ElementaryKapalama ElementaryKauluwelaKawananakoa MiddleKeelikolani MiddleKoko Head Elem.Kuhio ElementaryLiholihoLincoln ElementaryLunaliloManoa ElementaryMcKinley HighNiu Valley Middle NoelaniPaloloPuuhale ElementaryQueen Kaahumanu Elem.Roosevelt HighRoyalStevenson MiddleVoyager Charter SchoolWaikikiWashington Middle</value>
      <webElementGuid>10f108e4-83e8-472b-bbfb-0c7bdf5b591d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;school_filter_select&quot;)</value>
      <webElementGuid>28fdf174-d51c-4e88-b878-3b6e443d9feb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='school_filter_select']</value>
      <webElementGuid>f2ea4dae-3d0f-47c2-8db5-4f2c802a89b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-wrapper']/select</value>
      <webElementGuid>1a3a353b-89d0-4822-8936-1af43c146ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search...'])[1]/following::select[1]</value>
      <webElementGuid>f5cba28d-9a6c-4dce-8112-74e70ef14eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kauai'])[1]/following::select[1]</value>
      <webElementGuid>c364289e-0e13-4262-a193-1926c64f4e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student / School'])[1]/preceding::select[5]</value>
      <webElementGuid>e3910b51-4426-46e1-bc6a-493540c680b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>e0f85899-728f-4cd7-9b69-d741ce8fc3f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'school_filter_select' and (text() = 'All SchoolsABCABCAina HainaAliiolani ElementaryDole MiddleFarrington HighHahaione ElementaryHokulaniJarrett MiddleKaewai ElementaryKaewai ElementaryKaimuki HighKaimuki MiddleKaiser HighKaiulaniKalakaua MiddleKalani High Kalihi ESKalihi Kai Elem.Kalihi Uka SchoolKalihi Waena Elem.Kamiloiki ElementaryKapalama ElementaryKauluwelaKawananakoa MiddleKeelikolani MiddleKoko Head Elem.Kuhio ElementaryLiholihoLincoln ElementaryLunaliloManoa ElementaryMcKinley HighNiu Valley Middle NoelaniPaloloPuuhale ElementaryQueen Kaahumanu Elem.Roosevelt HighRoyalStevenson MiddleVoyager Charter SchoolWaikikiWashington Middle' or . = 'All SchoolsABCABCAina HainaAliiolani ElementaryDole MiddleFarrington HighHahaione ElementaryHokulaniJarrett MiddleKaewai ElementaryKaewai ElementaryKaimuki HighKaimuki MiddleKaiser HighKaiulaniKalakaua MiddleKalani High Kalihi ESKalihi Kai Elem.Kalihi Uka SchoolKalihi Waena Elem.Kamiloiki ElementaryKapalama ElementaryKauluwelaKawananakoa MiddleKeelikolani MiddleKoko Head Elem.Kuhio ElementaryLiholihoLincoln ElementaryLunaliloManoa ElementaryMcKinley HighNiu Valley Middle NoelaniPaloloPuuhale ElementaryQueen Kaahumanu Elem.Roosevelt HighRoyalStevenson MiddleVoyager Charter SchoolWaikikiWashington Middle')]</value>
      <webElementGuid>ed111e7f-0884-42bb-9d4e-1ade364d522b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
