<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>table_providerEmail</description>
   <name>table_providerEmail</name>
   <tag></tag>
   <elementGuidId>fb73a3b1-2a7c-4e0b-9a8f-4f1132ed05b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table/tbody/tr[${row}]/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
