<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>table_providerName</description>
   <name>table_providerName</name>
   <tag></tag>
   <elementGuidId>3a9d85f9-a198-455d-9342-85994a6f6b6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table/tbody/tr[${row}]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
