<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Other ActionsAdd SchoolAdd StudentAd_95a9b7</name>
   <tag></tag>
   <elementGuidId>552d4e14-950c-4631-a5b8-43312ee618ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='other-actions-dropdown']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#other-actions-dropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#other-actions-dropdown</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>075906ef-cbb7-4bb4-be92-cc1d2c7baf81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>other-actions-dropdown</value>
      <webElementGuid>6ca65d95-2fe3-4b11-91c5-c8ff1f54bd0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-stone-700 w-[100%] border-4 p-2</value>
      <webElementGuid>2a1e128a-fd81-4ed5-86f3-7ab4e0a40057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Other ActionsAdd SchoolAdd StudentAdd ProviderAdd WorkorderAdd SupervisorSave Bookmark</value>
      <webElementGuid>c6492959-3099-4d92-a990-4c93f7dbf02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;other-actions-dropdown&quot;)</value>
      <webElementGuid>ac2b57bb-7d93-49ea-b07e-794a7898f269</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='other-actions-dropdown']</value>
      <webElementGuid>555687df-9754-40d4-9f1c-3b51be591d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-wrapper']/select[5]</value>
      <webElementGuid>b1e85250-0829-410d-8bdf-c700df56744e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search...'])[1]/following::select[5]</value>
      <webElementGuid>7d2b7d80-6428-4aa9-a336-ac34b3368d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kauai'])[1]/following::select[5]</value>
      <webElementGuid>1d2fa215-1ee1-4b13-b4e0-817525295455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student / School'])[1]/preceding::select[1]</value>
      <webElementGuid>d1600c90-07e1-4727-ab42-83b6b14d8f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[5]</value>
      <webElementGuid>58c59847-ecea-4906-8faf-749681fd56b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'other-actions-dropdown' and (text() = 'Other ActionsAdd SchoolAdd StudentAdd ProviderAdd WorkorderAdd SupervisorSave Bookmark' or . = 'Other ActionsAdd SchoolAdd StudentAdd ProviderAdd WorkorderAdd SupervisorSave Bookmark')]</value>
      <webElementGuid>a4074a8a-b112-4df9-9e5a-eec3eb9f95b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
