<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Other Actions00000Add Leave of absen_0510bc</name>
   <tag></tag>
   <elementGuidId>a771d2b9-ecd4-4699-b8f3-07b51fe65df8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='other-actions-dropdown']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#other-actions-dropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#other-actions-dropdown</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>43caab65-da9e-4dc0-9885-9a3bf165287c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>other-actions-dropdown</value>
      <webElementGuid>f40dabe5-c99f-4b4a-84e3-ed5d06699f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-stone-700 w-[100%] border-4 p-2</value>
      <webElementGuid>3056909d-86d9-4eb8-bbb9-554a0ce1bfda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Other Actions00000Add Leave of absenceProviders Schools Student Details OSCER Work Orders Save Bookmark</value>
      <webElementGuid>ed49d3e8-3a93-4f32-ac84-24ebece1d684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;other-actions-dropdown&quot;)</value>
      <webElementGuid>9acd9712-9250-47fa-b3be-c9a0d25f0199</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='other-actions-dropdown']</value>
      <webElementGuid>b01e350c-44ff-4dab-8105-a6c1cb60dcaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-wrapper']/select[5]</value>
      <webElementGuid>81e7cd3b-f9d7-4194-8938-6c724d248cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search...'])[1]/following::select[5]</value>
      <webElementGuid>9aca90e3-978f-434c-a1d7-87c8f4de09bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kauai'])[1]/following::select[5]</value>
      <webElementGuid>415bac74-6e91-4e30-b0c4-18939ddea734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='School / Student'])[1]/preceding::select[1]</value>
      <webElementGuid>096a4f42-6cae-466d-9c5f-113625e8cffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0']/parent::*</value>
      <webElementGuid>8a77b7a0-c9c3-44c8-aa94-aab9c5ef80a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[5]</value>
      <webElementGuid>1e44661c-5c3a-4a7a-9c27-1618afa9cbf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'other-actions-dropdown' and (text() = 'Other Actions00000Add Leave of absenceProviders Schools Student Details OSCER Work Orders Save Bookmark' or . = 'Other Actions00000Add Leave of absenceProviders Schools Student Details OSCER Work Orders Save Bookmark')]</value>
      <webElementGuid>38119314-8c2b-4459-aa18-84c774c29fa1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
