<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_0</name>
   <tag></tag>
   <elementGuidId>76b8e582-ef20-4951-9dbd-40895cabee81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;0&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3fec3c72-2adf-4205-9e08-093a1e941bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>25563037-e2d9-4faa-af12-5950b388d88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>numpad col-start-2 flex h-[50px] w-[70px] items-center justify-center rounded-[15px] border bg-white text-lg disabled:opacity-50</value>
      <webElementGuid>1e42d3b1-476d-4005-b15d-9d77080fcfdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d474c803-13fa-4b01-9699-716336542b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numpadContainer&quot;)/button[@class=&quot;numpad col-start-2 flex h-[50px] w-[70px] items-center justify-center rounded-[15px] border bg-white text-lg disabled:opacity-50&quot;]</value>
      <webElementGuid>15c0b291-faa1-4b4d-b008-f88d6e2f0ea9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='0']</value>
      <webElementGuid>41c8e013-2b76-4449-8647-43dd4806963b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='numpadContainer']/button[10]</value>
      <webElementGuid>3a761bf1-bfcb-4fcc-b9b2-594d5484e479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::button[2]</value>
      <webElementGuid>958446bf-332c-481d-8f89-0648fad660a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot PIN'])[1]/preceding::button[3]</value>
      <webElementGuid>fcffdfa2-4892-4c97-870f-dffc04068020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0']/parent::*</value>
      <webElementGuid>fe0a3096-a4ea-4f9a-bb7a-4fc88d71f47f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[10]</value>
      <webElementGuid>e8a9f0a3-5453-4a76-85c6-953d65d64cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '0' or . = '0')]</value>
      <webElementGuid>55fdbd0d-7ce9-4efa-a2ac-7ff278f22e6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
