<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_7</name>
   <tag></tag>
   <elementGuidId>4dd76a62-2e16-4393-ba64-d14dcbd2837f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;7&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>12842ed2-f8d1-403a-8848-6aea04c7f310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>69bf3863-3112-44d4-ab11-31d9d2ef5ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>numpad flex h-[50px] w-[70px] items-center justify-center rounded-[15px] border bg-white text-lg disabled:opacity-50</value>
      <webElementGuid>4111bdb9-a578-4563-b135-fd22638ff975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>e07c4ab4-f3b7-471b-b7d8-675ae8b1c4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numpadContainer&quot;)/button[@class=&quot;numpad flex h-[50px] w-[70px] items-center justify-center rounded-[15px] border bg-white text-lg disabled:opacity-50&quot;]</value>
      <webElementGuid>6f5cb629-31df-4938-aa8c-7ba8ed0bfc80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='7']</value>
      <webElementGuid>2cada4ec-8cd2-44b8-94e6-b9cf8f14d5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='numpadContainer']/button[7]</value>
      <webElementGuid>149eea94-b0b5-4d9c-8322-e77be7947855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::button[5]</value>
      <webElementGuid>70212e91-d47c-4bac-a893-944f1a0869f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot PIN'])[1]/preceding::button[6]</value>
      <webElementGuid>30e64ad4-a686-4d62-bf98-282042407e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='7']/parent::*</value>
      <webElementGuid>f85373ed-2aac-42bf-a2c3-92db08e524eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[7]</value>
      <webElementGuid>5b61c4da-5836-44c9-b784-1466614d6f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '7' or . = '7')]</value>
      <webElementGuid>eb42979e-74a7-48f1-aaef-4760a38f1f04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
