<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_6</name>
   <tag></tag>
   <elementGuidId>b874a6ae-fc69-4d96-8d94-dc94ee1fb3b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;6&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>df11c0cd-1020-416c-b881-6f03b7832184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>779a703b-1c91-466c-8516-f4ede173e8f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>numpad flex h-[50px] w-[70px] items-center justify-center rounded-[15px] border bg-white text-lg disabled:opacity-50</value>
      <webElementGuid>179ca573-8c9e-4db9-832e-98f53640bb8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>eab6d14c-09b1-4b0f-bb4e-03106aee17d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numpadContainer&quot;)/button[@class=&quot;numpad flex h-[50px] w-[70px] items-center justify-center rounded-[15px] border bg-white text-lg disabled:opacity-50&quot;]</value>
      <webElementGuid>4329d580-b4ed-46a0-bcf5-781fdf2de575</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='6']</value>
      <webElementGuid>ccead777-4ea4-4c82-a326-c4baaf69a9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='numpadContainer']/button[6]</value>
      <webElementGuid>043d3fc5-2f5b-4394-be66-6bad3407878d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::button[6]</value>
      <webElementGuid>1c24667b-1860-425f-8086-08bd5197d473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot PIN'])[1]/preceding::button[7]</value>
      <webElementGuid>60eea27b-41c8-4bab-8d45-253545815bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='6']/parent::*</value>
      <webElementGuid>58e5257e-ad01-4219-a357-34cab6ebf9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[6]</value>
      <webElementGuid>5ff93e42-cb5a-4ca4-9040-06bf95343c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '6' or . = '6')]</value>
      <webElementGuid>a1257cdc-35df-4673-9f3b-375d29917f70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
