<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Mon</name>
   <tag></tag>
   <elementGuidId>6d94d905-1c1a-42aa-84ec-a42ce61b0866</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.flex.h-12.w-12.flex-col.items-center.justify-center.rounded-full.border.border-black.p-3.false</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='daysContainer']/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Mon 22&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e11abded-3047-4e71-9bb5-f8eba4eb669f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex h-12 w-12 flex-col items-center justify-center rounded-full border border-black p-3 false</value>
      <webElementGuid>6dda8c2f-868a-45d5-ba13-1f0e30d091b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mon22</value>
      <webElementGuid>4988e93f-3f9d-4db7-942a-7112b967df49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;daysContainer&quot;)/div[@class=&quot;flex items-end&quot;]/button[@class=&quot;flex h-12 w-12 flex-col items-center justify-center rounded-full border border-black p-3 false&quot;]</value>
      <webElementGuid>029405a7-7ce2-4eb8-9797-cdaabeb91a34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='daysContainer']/div/button</value>
      <webElementGuid>f930d3da-0459-48e0-9843-edaefb2ffbd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Week Ending:'])[1]/following::button[1]</value>
      <webElementGuid>a5d9ff62-b50f-4324-a1b7-895375a94578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::button[1]</value>
      <webElementGuid>31387e71-ffc3-415b-8d80-d97b7940dfab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>dd74943f-156d-4c8f-8aba-c55f40c6afa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Mon22' or . = 'Mon22')]</value>
      <webElementGuid>dc89fa50-096b-4c8e-9304-312e807be34e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
