<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_StudentsListContainer</name>
   <tag></tag>
   <elementGuidId>d9ba75a1-452f-43e6-b5bb-188dc9a3be2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='studentsListContainer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#studentsListContainer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;CKLHPS&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>748b3e0f-6d72-45cc-96b0-67669c8d9b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-3 grid grid-cols-4 gap-y-2</value>
      <webElementGuid>3667b26b-97f7-425e-a3c2-99a9d225c390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>studentsListContainer</value>
      <webElementGuid>2d2eae60-afdc-4f72-bca4-c226549701f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CKLHPS</value>
      <webElementGuid>07c1ec3e-458a-42ce-82e3-cd34aa4982f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;studentsListContainer&quot;)</value>
      <webElementGuid>fb8b09e8-81ac-4fbc-a2aa-7dcf0317408d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='studentsListContainer']</value>
      <webElementGuid>24ff3211-f60a-4a5f-9d93-f47aa06145c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[3]</value>
      <webElementGuid>41075249-849f-4662-bb22-ae1059ca0b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Week Ending:'])[1]/following::div[8]</value>
      <webElementGuid>58914764-9723-4244-bf9a-2fe77268489a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::div[10]</value>
      <webElementGuid>5f488555-4e93-421c-b7c7-d69535512ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>e55024d7-028d-4ef6-a39a-1072151911f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'studentsListContainer' and (text() = 'CKLHPS' or . = 'CKLHPS')]</value>
      <webElementGuid>b38bf55d-1f90-460a-ac42-a5b0d6d2e8e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
