<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Login_h-6 w-6</name>
   <tag></tag>
   <elementGuidId>f8204928-2d66-436d-8abf-621201c75947</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.h-6.w-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#deleteBtn</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2dfdd6a6-ae2e-497c-af02-5515327beae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-6 w-6</value>
      <webElementGuid>bf9a7da8-8151-438f-a8be-b95cbde7a4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./icons/delete.png</value>
      <webElementGuid>148a5cb7-6a91-4ae9-b1fd-e4aa6af055cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deleteBtn&quot;)/img[@class=&quot;h-6 w-6&quot;]</value>
      <webElementGuid>579b805b-e537-40fc-844f-868354b8174e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='deleteBtn']/img</value>
      <webElementGuid>6a57dd6b-f099-4912-a728-2b8be8d7dc9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[11]/img</value>
      <webElementGuid>5d27d4aa-9b30-4fab-8716-97679fbedcd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './icons/delete.png']</value>
      <webElementGuid>3058ad44-e26a-4f71-a46d-386eeda3f44c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
