<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>04efca81-7c04-4e77-aa84-9fd1181d6a55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='studentsListContainer']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.student.flex.flex-col.items-center > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#studentsListContainer img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>beea592d-8458-4286-bc27-4f260ee2f497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/avatar/184325194-4.png</value>
      <webElementGuid>7020f22d-ce82-4cae-a61a-0e77846dd390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;studentsListContainer&quot;)/div[@class=&quot;student flex flex-col items-center&quot;]/img[1]</value>
      <webElementGuid>3c78ace7-42b9-48d6-89d5-2ddf46a3d4fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='studentsListContainer']/div/img</value>
      <webElementGuid>cf296821-acf2-4de6-9f8d-ded14efc3b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>3bea95b0-dc18-4aaa-9c94-60b6a15a2464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/avatar/184325194-4.png']</value>
      <webElementGuid>5180386e-068f-4719-aa5c-b831b386f117</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
