<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Horizontal</name>
   <tag></tag>
   <elementGuidId>6608aa85-2d67-46ec-a266-8819ed01e720</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.my-1.flex.justify-between</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=&quot;Horizontal&quot;i >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>768412fd-e07c-4986-9e1f-3750fc473c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-1 flex justify-between</value>
      <webElementGuid>9adae490-d42d-49ae-9267-e599c2a571ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Horizontal</value>
      <webElementGuid>0e6c56d5-10b2-470c-b437-cb373033fb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;px-3&quot;]/div[@class=&quot;flex h-screen flex-col&quot;]/div[@class=&quot;border-stone-300 sticky top-0 z-50 flex-shrink-0 border-b bg-white&quot;]/div[@class=&quot;my-1 flex justify-between&quot;]</value>
      <webElementGuid>8b0f03af-662a-4b75-97c3-139ca60eaa0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div</value>
      <webElementGuid>2333ec60-9ae8-4455-be77-16d66113079d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::div[2]</value>
      <webElementGuid>7ff481b4-3541-4ce0-bbe5-ed96faae606e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::div[2]</value>
      <webElementGuid>c0a66ea3-0638-4b7b-8749-2e597b2e9e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Honolulu'])[1]/preceding::div[5]</value>
      <webElementGuid>7eb9e2c8-b200-4b5e-a546-5b4aaffa76e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>99eb51ee-714d-43f6-a910-3ce0eb8207d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Horizontal' or . = 'Horizontal')]</value>
      <webElementGuid>28a3ed69-6764-444e-ad09-6cb765e5676f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
