<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Provider_fixed left-0 top-0 z-50 flex h_183691</name>
   <tag></tag>
   <elementGuidId>755509a6-09a9-40fe-92f6-6c5cefd7eee0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.fixed.left-0.top-0.z-50.flex.h-full.w-full.items-center.justify-center.bg-black.bg-opacity-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.fixed</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c50caf24-d7c9-404f-b02e-d8d9f009c6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fixed left-0 top-0 z-50 flex h-full w-full items-center justify-center bg-black bg-opacity-5</value>
      <webElementGuid>f58d1fc8-6263-4e5c-a3d2-f4f1894a1adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;px-3&quot;]/div[@class=&quot;h-screen flex flex-col&quot;]/div[@class=&quot;flex-1 border-stone-700 flex my-[2em] min-h-[55vh] w-[100%] flex-col justify-between border-2 overflow-x-auto&quot;]/div[@class=&quot;fixed left-0 top-0 z-50 flex h-full w-full items-center justify-center bg-black bg-opacity-5&quot;]</value>
      <webElementGuid>a7fee9e3-484f-4310-8228-ca3736479638</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[2]/div</value>
      <webElementGuid>e8fc4c7b-f9d6-4db9-a019-5aca7cfb1c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provider'])[1]/following::div[1]</value>
      <webElementGuid>051c2bdd-a7c5-4448-ab06-c2200cfe1588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/following::div[2]</value>
      <webElementGuid>21b2016f-ce8c-4e01-b8b4-17466d73b315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;&lt;'])[1]/preceding::div[1]</value>
      <webElementGuid>50cb93a9-bde7-4fd5-9edc-04c422e577ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[1]/preceding::div[1]</value>
      <webElementGuid>9a8562fa-e54f-4660-ab46-93a9565fb48c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>aaa4a139-3964-4231-a1c6-7c05061049e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
