<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1125 thru 1129This WeekNext WeekMond_ed6515</name>
   <tag></tag>
   <elementGuidId>3d25a280-8d58-4045-936c-8861ad111c96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#date_filter_select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='date_filter_select']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#date_filter_select</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e260608b-292e-492c-8940-f63df0f9131c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-stone-700 w-[100%] border-4 p-2</value>
      <webElementGuid>818955a6-c5d4-4ec4-bdf8-e16215b332cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>date_filter_select</value>
      <webElementGuid>9246a8fd-529e-4dc3-badd-1b06b3cfab42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>11/25 thru 11/29This WeekNext WeekMondayTuesdayWednesdayThursdayFridayNovemberDecemberJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctober</value>
      <webElementGuid>9973d3c2-7c9c-42cb-80b8-7b987ce07562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;date_filter_select&quot;)</value>
      <webElementGuid>824eeb6f-fffc-44f6-8065-8f8cbb3021d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='date_filter_select']</value>
      <webElementGuid>a62b5d98-6d17-4507-ac50-0f8cfd9ced2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-wrapper']/select[3]</value>
      <webElementGuid>b1e95c50-892b-4002-a05c-0b2e8a31dc59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search...'])[1]/following::select[3]</value>
      <webElementGuid>ef164df2-0311-4256-84ef-1134c4623912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kauai'])[1]/following::select[3]</value>
      <webElementGuid>7855dbea-9d46-484e-aae8-ca6333f295ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student / School'])[1]/preceding::select[3]</value>
      <webElementGuid>f34f3eb9-0c0a-4560-9f8b-8252193cb5dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[3]</value>
      <webElementGuid>442c4582-9db5-4c1e-a0e1-473aca5eb06a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'date_filter_select' and (text() = '11/25 thru 11/29This WeekNext WeekMondayTuesdayWednesdayThursdayFridayNovemberDecemberJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctober' or . = '11/25 thru 11/29This WeekNext WeekMondayTuesdayWednesdayThursdayFridayNovemberDecemberJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctober')]</value>
      <webElementGuid>9c26a8aa-2d90-41cf-8b71-575b99eeb98a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
